<?php 
 if( ! class_exists( 'AFAQCBC_q_a_faq_Setting_Question_Metabox' ) ) {
	 		/*
* خيارات الايكونه واللالوان تبعتها الخاصه بالسءال
*/
	class AFAQCBC_q_a_faq_Setting_Question_Metabox {

		public function __construct() {

			if ( is_admin() ) {
				add_action( 'load-post.php',     array( $this, 'init_metabox' ) );
				add_action( 'load-post-new.php', array( $this, 'init_metabox' ) );
			}

		}
		


		public function init_metabox() {
			add_action( 'add_meta_boxes',        array( $this, 'add_metabox' )         );
			add_action( 'save_post',             array( $this, 'save_metabox' ), 10, 2 );
			add_action( 'admin_enqueue_scripts', array( $this, 'load_scripts_styles')  );
			add_action('admin_enqueue_scripts', array($this,'faq_css'));
			
		}
		/*
* بناء منطقة داخل منطقة إضافة او تعديل سؤال لتحتوي على الخيارات
*/
		public function add_metabox() {

			add_meta_box(
				'post_pubic_Sitting',
				esc_html__( 'Public Question Sitting', 'advanced-faq-creator-by-category' ),
				array( $this, 'render_metabox' ),
				'question',
				'advanced',
				'default'
			);

		}
		/*
* الخيارات الخاصه بالسؤال من ايقونه ولون  الايقونه 
*/
		public function render_metabox( $post ) {
			add_action( 'admin_footer',         array( $this, 'sitting_field_js' )      );

			$q_icon_color = esc_attr(get_post_meta( $post->ID, 'q_icon_color', true ));
			$icon_font_select = esc_attr(get_post_meta( $post->ID, 'icon_font_select', true ));

			if( empty( $q_icon_color ) ) $q_icon_color = '#000000';
			if( empty( $icon_font_select ) ) $icon_font_select = 'no-icon';

			?>
			<table class="form-table">

				<tr>
                    <td><label for="q_icon_color" class="gwp_pc_primary_color_label"><?php echo esc_html__( 'Icon color', 'advanced-faq-creator-by-category' );?></label></td>
                    <td>
                        <input type="text" id="q_icon_color" name="q_icon_color" class="gwp_pc_primary_color_field"  value="<?php echo  esc_attr__( $q_icon_color );?>">
                        <p class="description"><?php echo esc_html__( 'Select icon color', 'advanced-faq-creator-by-category' );?></p>
                    </td>
					
					<th><label for="icon_font_select"><?php echo esc_html__( 'Select icon', 'advanced-faq-creator-by-category' );?></label></th>
					<td>
						
						<select id="icon_font_select" class="select2-icon" name="icon_font_select" style="font-family:'FontAwesome';    display: none;">
							<?php
								$i = 0;
								foreach($this->q_icons_aw_list() as $key=>$val){
									if($icon_font_select == $key || ($icon_font_select == '' && $i == 0)){?>
										<option selected value="<?php echo esc_attr($key);?>" data-icon="<?php echo esc_attr($key);?>"><?php echo esc_attr($val);?></option>';
									<?php }else{ ?>
										<option value="<?php echo esc_attr($key);?>" data-icon="<?php echo esc_attr($key);?>"><?php echo esc_attr($val);?></option>';
									<?php }
									$i++;
								}
							?>
							</select>
						<p class="description"><?php  echo esc_html__( 'Select Paragraph Font Weight', 'advanced-faq-creator-by-category' );?> </p>
					</td>
				</tr>

			</table>
			<?php

		}
		/*
* حفظ الخيارات الي جايه من السكشن الي فوق
*/
		public function save_metabox( $post_id, $post ) {

			
			if ( ! current_user_can( 'edit_post', $post_id ) )
				return;

			if ( wp_is_post_autosave( $post_id ) )
				return;

			if ( wp_is_post_revision( $post_id ) )
				return;

			$q_icon_color = isset( $_POST[ 'q_icon_color' ] ) ? sanitize_text_field( $_POST[ 'q_icon_color' ] ) : '';
			$icon_font_select = isset( $_POST[ 'icon_font_select' ] ) ? sanitize_text_field( $_POST[ 'icon_font_select' ] ) : '';

			update_post_meta( $post_id, 'q_icon_color', $q_icon_color );
			update_post_meta( $post_id, 'icon_font_select', $icon_font_select );

		}
				/*
* مكتبات الجافا سكربت
*/
		public function load_scripts_styles() {
			wp_enqueue_script( 'wp-color-picker' );
			wp_enqueue_style( 'wp-color-picker' );
		}
				/*
* رموز الايقونات الخاصه بالفونت اوسم لمنطقة السؤال
*/
		function q_icons_aw_list(){
			return array (
					'' => esc_attr__( '', 'advanced-faq-creator-by-category' ),
					'fab fa-500px' => esc_attr__( '500px', 'advanced-faq-creator-by-category' ),
					'fab fa-accessible-icon' => esc_attr__( 'accessible-icon', 'advanced-faq-creator-by-category' ),
					'fab fa-accusoft' => esc_attr__( 'accusoft', 'advanced-faq-creator-by-category' ),
					'fas fa-address-book' => esc_attr__( 'address-book', 'advanced-faq-creator-by-category' ),
					'far fa-address-book' => esc_attr__( 'address-book', 'advanced-faq-creator-by-category' ),
					'fas fa-address-card' => esc_attr__( 'address-card', 'advanced-faq-creator-by-category' ),
					'far fa-address-card' => esc_attr__( 'address-card', 'advanced-faq-creator-by-category' ),
					'fas fa-adjust' => esc_attr__( 'adjust', 'advanced-faq-creator-by-category' ),
					'fab fa-adn' => esc_attr__( 'adn', 'advanced-faq-creator-by-category' ),
					'fab fa-adversal' => esc_attr__( 'adversal', 'advanced-faq-creator-by-category' ),
					'fab fa-affiliatetheme' => esc_attr__( 'affiliatetheme', 'advanced-faq-creator-by-category' ),
					'fab fa-algolia' => esc_attr__( 'algolia', 'advanced-faq-creator-by-category' ),
					'fas fa-align-center' => esc_attr__( 'align-center', 'advanced-faq-creator-by-category' ),
					'fas fa-align-justify' => esc_attr__( 'align-justify', 'advanced-faq-creator-by-category' ),
					'fas fa-align-left' => esc_attr__( 'align-left', 'advanced-faq-creator-by-category' ),
					'fas fa-align-right' => esc_attr__( 'align-right', 'advanced-faq-creator-by-category' ),
					'fas fa-allergies' => esc_attr__( 'allergies', 'advanced-faq-creator-by-category' ),
					'fab fa-amazon' => esc_attr__( 'amazon', 'advanced-faq-creator-by-category' ),
					'fab fa-amazon-pay' => esc_attr__( 'amazon-pay', 'advanced-faq-creator-by-category' ),
					'fas fa-ambulance' => esc_attr__( 'ambulance', 'advanced-faq-creator-by-category' ),
					'fas fa-american-sign-language-interpreting' => esc_attr__( 'american-sign-language-interpreting', 'advanced-faq-creator-by-category' ),
					'fab fa-amilia' => esc_attr__( 'amilia', 'advanced-faq-creator-by-category' ),
					'fas fa-anchor' => esc_attr__( 'anchor', 'advanced-faq-creator-by-category' ),
					'fab fa-android' => esc_attr__( 'android', 'advanced-faq-creator-by-category' ),
					'fab fa-angellist' => esc_attr__( 'angellist', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-double-down' => esc_attr__( 'angle-double-down', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-double-left' => esc_attr__( 'angle-double-left', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-double-right' => esc_attr__( 'angle-double-right', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-double-up' => esc_attr__( 'angle-double-up', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-down' => esc_attr__( 'angle-down', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-left' => esc_attr__( 'angle-left', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-right' => esc_attr__( 'angle-right', 'advanced-faq-creator-by-category' ),
					'fas fa-angle-up' => esc_attr__( 'angle-up', 'advanced-faq-creator-by-category' ),
					'fab fa-angrycreative' => esc_attr__( 'angrycreative', 'advanced-faq-creator-by-category' ),
					'fab fa-angular' => esc_attr__( 'angular', 'advanced-faq-creator-by-category' ),
					'fab fa-app-store' => esc_attr__( 'app-store', 'advanced-faq-creator-by-category' ),
					'fab fa-app-store-ios' => esc_attr__( 'app-store-ios', 'advanced-faq-creator-by-category' ),
					'fab fa-apper' => esc_attr__( 'apper', 'advanced-faq-creator-by-category' ),
					'fab fa-apple' => esc_attr__( 'apple', 'advanced-faq-creator-by-category' ),
					'fab fa-apple-pay' => esc_attr__( 'apple-pay', 'advanced-faq-creator-by-category' ),
					'fas fa-archive' => esc_attr__( 'archive', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-alt-circle-down' => esc_attr__( 'arrow-alt-circle-down', 'advanced-faq-creator-by-category' ),
					'far fa-arrow-alt-circle-down' => esc_attr__( 'arrow-alt-circle-down', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-alt-circle-left' => esc_attr__( 'arrow-alt-circle-left', 'advanced-faq-creator-by-category' ),
					'far fa-arrow-alt-circle-left' => esc_attr__( 'arrow-alt-circle-left', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-alt-circle-right' => esc_attr__( 'arrow-alt-circle-right', 'advanced-faq-creator-by-category' ),
					'far fa-arrow-alt-circle-right' => esc_attr__( 'arrow-alt-circle-right', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-alt-circle-up' => esc_attr__( 'arrow-alt-circle-up', 'advanced-faq-creator-by-category' ),
					'far fa-arrow-alt-circle-up' => esc_attr__( 'arrow-alt-circle-up', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-circle-down' => esc_attr__( 'arrow-circle-down', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-circle-left' => esc_attr__( 'arrow-circle-left', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-circle-right' => esc_attr__( 'arrow-circle-right', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-circle-up' => esc_attr__( 'arrow-circle-up', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-down' => esc_attr__( 'arrow-down', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-left' => esc_attr__( 'arrow-left', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-right' => esc_attr__( 'arrow-right', 'advanced-faq-creator-by-category' ),
					'fas fa-arrow-up' => esc_attr__( 'arrow-up', 'advanced-faq-creator-by-category' ),
					'fas fa-arrows-alt' => esc_attr__( 'arrows-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-arrows-alt-h' => esc_attr__( 'arrows-alt-h', 'advanced-faq-creator-by-category' ),
					'fas fa-arrows-alt-v' => esc_attr__( 'arrows-alt-v', 'advanced-faq-creator-by-category' ),
					'fas fa-assistive-listening-systems' => esc_attr__( 'assistive-listening-systems', 'advanced-faq-creator-by-category' ),
					'fas fa-asterisk' => esc_attr__( 'asterisk', 'advanced-faq-creator-by-category' ),
					'fab fa-asymmetrik' => esc_attr__( 'asymmetrik', 'advanced-faq-creator-by-category' ),
					'fas fa-at' => esc_attr__( 'at', 'advanced-faq-creator-by-category' ),
					'fab fa-audible' => esc_attr__( 'audible', 'advanced-faq-creator-by-category' ),
					'fas fa-audio-description' => esc_attr__( 'audio-description', 'advanced-faq-creator-by-category' ),
					'fab fa-autoprefixer' => esc_attr__( 'autoprefixer', 'advanced-faq-creator-by-category' ),
					'fab fa-avianex' => esc_attr__( 'avianex', 'advanced-faq-creator-by-category' ),
					'fab fa-aviato' => esc_attr__( 'aviato', 'advanced-faq-creator-by-category' ),
					'fab fa-aws' => esc_attr__( 'aws', 'advanced-faq-creator-by-category' ),
					'fas fa-backward' => esc_attr__( 'backward', 'advanced-faq-creator-by-category' ),
					'fas fa-balance-scale' => esc_attr__( 'balance-scale', 'advanced-faq-creator-by-category' ),
					'fas fa-ban' => esc_attr__( 'ban', 'advanced-faq-creator-by-category' ),
					'fas fa-band-aid' => esc_attr__( 'band-aid', 'advanced-faq-creator-by-category' ),
					'fab fa-bandcamp' => esc_attr__( 'bandcamp', 'advanced-faq-creator-by-category' ),
					'fas fa-barcode' => esc_attr__( 'barcode', 'advanced-faq-creator-by-category' ),
					'fas fa-bars' => esc_attr__( 'bars', 'advanced-faq-creator-by-category' ),
					'fas fa-baseball-ball' => esc_attr__( 'baseball-ball', 'advanced-faq-creator-by-category' ),
					'fas fa-basketball-ball' => esc_attr__( 'basketball-ball', 'advanced-faq-creator-by-category' ),
					'fas fa-bath' => esc_attr__( 'bath', 'advanced-faq-creator-by-category' ),
					'fas fa-battery-empty' => esc_attr__( 'battery-empty', 'advanced-faq-creator-by-category' ),
					'fas fa-battery-full' => esc_attr__( 'battery-full', 'advanced-faq-creator-by-category' ),
					'fas fa-battery-half' => esc_attr__( 'battery-half', 'advanced-faq-creator-by-category' ),
					'fas fa-battery-quarter' => esc_attr__( 'battery-quarter', 'advanced-faq-creator-by-category' ),
					'fas fa-battery-three-quarters' => esc_attr__( 'battery-three-quarters', 'advanced-faq-creator-by-category' ),
					'fas fa-bed' => esc_attr__( 'bed', 'advanced-faq-creator-by-category' ),
					'fas fa-beer' => esc_attr__( 'beer', 'advanced-faq-creator-by-category' ),
					'fab fa-behance' => esc_attr__( 'behance', 'advanced-faq-creator-by-category' ),
					'fab fa-behance-square' => esc_attr__( 'behance-square', 'advanced-faq-creator-by-category' ),
					'fas fa-bell' => esc_attr__( 'bell', 'advanced-faq-creator-by-category' ),
					'far fa-bell' => esc_attr__( 'bell', 'advanced-faq-creator-by-category' ),
					'fas fa-bell-slash' => esc_attr__( 'bell-slash', 'advanced-faq-creator-by-category' ),
					'far fa-bell-slash' => esc_attr__( 'bell-slash', 'advanced-faq-creator-by-category' ),
					'fas fa-bicycle' => esc_attr__( 'bicycle', 'advanced-faq-creator-by-category' ),
					'fab fa-bimobject' => esc_attr__( 'bimobject', 'advanced-faq-creator-by-category' ),
					'fas fa-binoculars' => esc_attr__( 'binoculars', 'advanced-faq-creator-by-category' ),
					'fas fa-birthday-cake' => esc_attr__( 'birthday-cake', 'advanced-faq-creator-by-category' ),
					'fab fa-bitbucket' => esc_attr__( 'bitbucket', 'advanced-faq-creator-by-category' ),
					'fab fa-bitcoin' => esc_attr__( 'bitcoin', 'advanced-faq-creator-by-category' ),
					'fab fa-bity' => esc_attr__( 'bity', 'advanced-faq-creator-by-category' ),
					'fab fa-black-tie' => esc_attr__( 'black-tie', 'advanced-faq-creator-by-category' ),
					'fab fa-blackberry' => esc_attr__( 'blackberry', 'advanced-faq-creator-by-category' ),
					'fas fa-blind' => esc_attr__( 'blind', 'advanced-faq-creator-by-category' ),
					'fab fa-blogger' => esc_attr__( 'blogger', 'advanced-faq-creator-by-category' ),
					'fab fa-blogger-b' => esc_attr__( 'blogger-b', 'advanced-faq-creator-by-category' ),
					'fab fa-bluetooth' => esc_attr__( 'bluetooth', 'advanced-faq-creator-by-category' ),
					'fab fa-bluetooth-b' => esc_attr__( 'bluetooth-b', 'advanced-faq-creator-by-category' ),
					'fas fa-bold' => esc_attr__( 'bold', 'advanced-faq-creator-by-category' ),
					'fas fa-bolt' => esc_attr__( 'bolt', 'advanced-faq-creator-by-category' ),
					'fas fa-bomb' => esc_attr__( 'bomb', 'advanced-faq-creator-by-category' ),
					'fas fa-book' => esc_attr__( 'book', 'advanced-faq-creator-by-category' ),
					'fas fa-bookmark' => esc_attr__( 'bookmark', 'advanced-faq-creator-by-category' ),
					'far fa-bookmark' => esc_attr__( 'bookmark', 'advanced-faq-creator-by-category' ),
					'fas fa-bowling-ball' => esc_attr__( 'bowling-ball', 'advanced-faq-creator-by-category' ),
					'fas fa-box' => esc_attr__( 'box', 'advanced-faq-creator-by-category' ),
					'fas fa-box-open' => esc_attr__( 'box-open', 'advanced-faq-creator-by-category' ),
					'fas fa-boxes' => esc_attr__( 'boxes', 'advanced-faq-creator-by-category' ),
					'fas fa-braille' => esc_attr__( 'braille', 'advanced-faq-creator-by-category' ),
					'fas fa-briefcase' => esc_attr__( 'briefcase', 'advanced-faq-creator-by-category' ),
					'fas fa-briefcase-medical' => esc_attr__( 'briefcase-medical', 'advanced-faq-creator-by-category' ),
					'fab fa-btc' => esc_attr__( 'btc', 'advanced-faq-creator-by-category' ),
					'fas fa-bug' => esc_attr__( 'bug', 'advanced-faq-creator-by-category' ),
					'fas fa-building' => esc_attr__( 'building', 'advanced-faq-creator-by-category' ),
					'far fa-building' => esc_attr__( 'building', 'advanced-faq-creator-by-category' ),
					'fas fa-bullhorn' => esc_attr__( 'bullhorn', 'advanced-faq-creator-by-category' ),
					'fas fa-bullseye' => esc_attr__( 'bullseye', 'advanced-faq-creator-by-category' ),
					'fas fa-burn' => esc_attr__( 'burn', 'advanced-faq-creator-by-category' ),
					'fab fa-buromobelexperte' => esc_attr__( 'buromobelexperte', 'advanced-faq-creator-by-category' ),
					'fas fa-bus' => esc_attr__( 'bus', 'advanced-faq-creator-by-category' ),
					'fab fa-buysellads' => esc_attr__( 'buysellads', 'advanced-faq-creator-by-category' ),
					'fas fa-calculator' => esc_attr__( 'calculator', 'advanced-faq-creator-by-category' ),
					'fas fa-calendar' => esc_attr__( 'calendar', 'advanced-faq-creator-by-category' ),
					'far fa-calendar' => esc_attr__( 'calendar', 'advanced-faq-creator-by-category' ),
					'fas fa-calendar-alt' => esc_attr__( 'calendar-alt', 'advanced-faq-creator-by-category' ),
					'far fa-calendar-alt' => esc_attr__( 'calendar-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-calendar-check' => esc_attr__( 'calendar-check', 'advanced-faq-creator-by-category' ),
					'far fa-calendar-check' => esc_attr__( 'calendar-check', 'advanced-faq-creator-by-category' ),
					'fas fa-calendar-minus' => esc_attr__( 'calendar-minus', 'advanced-faq-creator-by-category' ),
					'far fa-calendar-minus' => esc_attr__( 'calendar-minus', 'advanced-faq-creator-by-category' ),
					'fas fa-calendar-plus' => esc_attr__( 'calendar-plus', 'advanced-faq-creator-by-category' ),
					'far fa-calendar-plus' => esc_attr__( 'calendar-plus', 'advanced-faq-creator-by-category' ),
					'fas fa-calendar-times' => esc_attr__( 'calendar-times', 'advanced-faq-creator-by-category' ),
					'far fa-calendar-times' => esc_attr__( 'calendar-times', 'advanced-faq-creator-by-category' ),
					'fas fa-camera' => esc_attr__( 'camera', 'advanced-faq-creator-by-category' ),
					'fas fa-camera-retro' => esc_attr__( 'camera-retro', 'advanced-faq-creator-by-category' ),
					'fas fa-capsules' => esc_attr__( 'capsules', 'advanced-faq-creator-by-category' ),
					'fas fa-car' => esc_attr__( 'car', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-down' => esc_attr__( 'caret-down', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-left' => esc_attr__( 'caret-left', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-right' => esc_attr__( 'caret-right', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-square-down' => esc_attr__( 'caret-square-down', 'advanced-faq-creator-by-category' ),
					'far fa-caret-square-down' => esc_attr__( 'caret-square-down', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-square-left' => esc_attr__( 'caret-square-left', 'advanced-faq-creator-by-category' ),
					'far fa-caret-square-left' => esc_attr__( 'caret-square-left', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-square-right' => esc_attr__( 'caret-square-right', 'advanced-faq-creator-by-category' ),
					'far fa-caret-square-right' => esc_attr__( 'caret-square-right', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-square-up' => esc_attr__( 'caret-square-up', 'advanced-faq-creator-by-category' ),
					'far fa-caret-square-up' => esc_attr__( 'caret-square-up', 'advanced-faq-creator-by-category' ),
					'fas fa-caret-up' => esc_attr__( 'caret-up', 'advanced-faq-creator-by-category' ),
					'fas fa-cart-arrow-down' => esc_attr__( 'cart-arrow-down', 'advanced-faq-creator-by-category' ),
					'fas fa-cart-plus' => esc_attr__( 'cart-plus', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-amazon-pay' => esc_attr__( 'cc-amazon-pay', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-amex' => esc_attr__( 'cc-amex', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-apple-pay' => esc_attr__( 'cc-apple-pay', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-diners-club' => esc_attr__( 'cc-diners-club', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-discover' => esc_attr__( 'cc-discover', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-jcb' => esc_attr__( 'cc-jcb', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-mastercard' => esc_attr__( 'cc-mastercard', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-paypal' => esc_attr__( 'cc-paypal', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-stripe' => esc_attr__( 'cc-stripe', 'advanced-faq-creator-by-category' ),
					'fab fa-cc-visa' => esc_attr__( 'cc-visa', 'advanced-faq-creator-by-category' ),
					'fab fa-centercode' => esc_attr__( 'centercode', 'advanced-faq-creator-by-category' ),
					'fas fa-certificate' => esc_attr__( 'certificate', 'advanced-faq-creator-by-category' ),
					'fas fa-chart-area' => esc_attr__( 'chart-area', 'advanced-faq-creator-by-category' ),
					'fas fa-chart-bar' => esc_attr__( 'chart-bar', 'advanced-faq-creator-by-category' ),
					'far fa-chart-bar' => esc_attr__( 'chart-bar', 'advanced-faq-creator-by-category' ),
					'fas fa-chart-line' => esc_attr__( 'chart-line', 'advanced-faq-creator-by-category' ),
					'fas fa-chart-pie' => esc_attr__( 'chart-pie', 'advanced-faq-creator-by-category' ),
					'fas fa-check' => esc_attr__( 'check', 'advanced-faq-creator-by-category' ),
					'fas fa-check-circle' => esc_attr__( 'check-circle', 'advanced-faq-creator-by-category' ),
					'far fa-check-circle' => esc_attr__( 'check-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-check-square' => esc_attr__( 'check-square', 'advanced-faq-creator-by-category' ),
					'far fa-check-square' => esc_attr__( 'check-square', 'advanced-faq-creator-by-category' ),
					'fas fa-chess' => esc_attr__( 'chess', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-bishop' => esc_attr__( 'chess-bishop', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-board' => esc_attr__( 'chess-board', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-king' => esc_attr__( 'chess-king', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-knight' => esc_attr__( 'chess-knight', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-pawn' => esc_attr__( 'chess-pawn', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-queen' => esc_attr__( 'chess-queen', 'advanced-faq-creator-by-category' ),
					'fas fa-chess-rook' => esc_attr__( 'chess-rook', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-circle-down' => esc_attr__( 'chevron-circle-down', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-circle-left' => esc_attr__( 'chevron-circle-left', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-circle-right' => esc_attr__( 'chevron-circle-right', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-circle-up' => esc_attr__( 'chevron-circle-up', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-down' => esc_attr__( 'chevron-down', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-left' => esc_attr__( 'chevron-left', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-right' => esc_attr__( 'chevron-right', 'advanced-faq-creator-by-category' ),
					'fas fa-chevron-up' => esc_attr__( 'chevron-up', 'advanced-faq-creator-by-category' ),
					'fas fa-child' => esc_attr__( 'child', 'advanced-faq-creator-by-category' ),
					'fab fa-chrome' => esc_attr__( 'chrome', 'advanced-faq-creator-by-category' ),
					'fas fa-circle' => esc_attr__( 'circle', 'advanced-faq-creator-by-category' ),
					'far fa-circle' => esc_attr__( 'circle', 'advanced-faq-creator-by-category' ),
					'fas fa-circle-notch' => esc_attr__( 'circle-notch', 'advanced-faq-creator-by-category' ),
					'fas fa-clipboard' => esc_attr__( 'clipboard', 'advanced-faq-creator-by-category' ),
					'far fa-clipboard' => esc_attr__( 'clipboard', 'advanced-faq-creator-by-category' ),
					'fas fa-clipboard-check' => esc_attr__( 'clipboard-check', 'advanced-faq-creator-by-category' ),
					'fas fa-clipboard-list' => esc_attr__( 'clipboard-list', 'advanced-faq-creator-by-category' ),
					'fas fa-clock' => esc_attr__( 'clock', 'advanced-faq-creator-by-category' ),
					'far fa-clock' => esc_attr__( 'clock', 'advanced-faq-creator-by-category' ),
					'fas fa-clone' => esc_attr__( 'clone', 'advanced-faq-creator-by-category' ),
					'far fa-clone' => esc_attr__( 'clone', 'advanced-faq-creator-by-category' ),
					'fas fa-closed-captioning' => esc_attr__( 'closed-captioning', 'advanced-faq-creator-by-category' ),
					'far fa-closed-captioning' => esc_attr__( 'closed-captioning', 'advanced-faq-creator-by-category' ),
					'fas fa-cloud' => esc_attr__( 'cloud', 'advanced-faq-creator-by-category' ),
					'fas fa-cloud-download-alt' => esc_attr__( 'cloud-download-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-cloud-upload-alt' => esc_attr__( 'cloud-upload-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-cloudscale' => esc_attr__( 'cloudscale', 'advanced-faq-creator-by-category' ),
					'fab fa-cloudsmith' => esc_attr__( 'cloudsmith', 'advanced-faq-creator-by-category' ),
					'fab fa-cloudversify' => esc_attr__( 'cloudversify', 'advanced-faq-creator-by-category' ),
					'fas fa-code' => esc_attr__( 'code', 'advanced-faq-creator-by-category' ),
					'fas fa-code-branch' => esc_attr__( 'code-branch', 'advanced-faq-creator-by-category' ),
					'fab fa-codepen' => esc_attr__( 'codepen', 'advanced-faq-creator-by-category' ),
					'fab fa-codiepie' => esc_attr__( 'codiepie', 'advanced-faq-creator-by-category' ),
					'fas fa-coffee' => esc_attr__( 'coffee', 'advanced-faq-creator-by-category' ),
					'fas fa-cog' => esc_attr__( 'cog', 'advanced-faq-creator-by-category' ),
					'fas fa-cogs' => esc_attr__( 'cogs', 'advanced-faq-creator-by-category' ),
					'fas fa-columns' => esc_attr__( 'columns', 'advanced-faq-creator-by-category' ),
					'fas fa-comment' => esc_attr__( 'comment', 'advanced-faq-creator-by-category' ),
					'far fa-comment' => esc_attr__( 'comment', 'advanced-faq-creator-by-category' ),
					'fas fa-comment-alt' => esc_attr__( 'comment-alt', 'advanced-faq-creator-by-category' ),
					'far fa-comment-alt' => esc_attr__( 'comment-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-comment-dots' => esc_attr__( 'comment-dots', 'advanced-faq-creator-by-category' ),
					'fas fa-comment-slash' => esc_attr__( 'comment-slash', 'advanced-faq-creator-by-category' ),
					'fas fa-comments' => esc_attr__( 'comments', 'advanced-faq-creator-by-category' ),
					'far fa-comments' => esc_attr__( 'comments', 'advanced-faq-creator-by-category' ),
					'fas fa-compass' => esc_attr__( 'compass', 'advanced-faq-creator-by-category' ),
					'far fa-compass' => esc_attr__( 'compass', 'advanced-faq-creator-by-category' ),
					'fas fa-compress' => esc_attr__( 'compress', 'advanced-faq-creator-by-category' ),
					'fab fa-connectdevelop' => esc_attr__( 'connectdevelop', 'advanced-faq-creator-by-category' ),
					'fab fa-contao' => esc_attr__( 'contao', 'advanced-faq-creator-by-category' ),
					'fas fa-copy' => esc_attr__( 'copy', 'advanced-faq-creator-by-category' ),
					'far fa-copy' => esc_attr__( 'copy', 'advanced-faq-creator-by-category' ),
					'fas fa-copyright' => esc_attr__( 'copyright', 'advanced-faq-creator-by-category' ),
					'far fa-copyright' => esc_attr__( 'copyright', 'advanced-faq-creator-by-category' ),
					'fas fa-couch' => esc_attr__( 'couch', 'advanced-faq-creator-by-category' ),
					'fab fa-cpanel' => esc_attr__( 'cpanel', 'advanced-faq-creator-by-category' ),
					'fab fa-creative-commons' => esc_attr__( 'creative-commons', 'advanced-faq-creator-by-category' ),
					'fas fa-credit-card' => esc_attr__( 'credit-card', 'advanced-faq-creator-by-category' ),
					'far fa-credit-card' => esc_attr__( 'credit-card', 'advanced-faq-creator-by-category' ),
					'fas fa-crop' => esc_attr__( 'crop', 'advanced-faq-creator-by-category' ),
					'fas fa-crosshairs' => esc_attr__( 'crosshairs', 'advanced-faq-creator-by-category' ),
					'fab fa-css3' => esc_attr__( 'css3', 'advanced-faq-creator-by-category' ),
					'fab fa-css3-alt' => esc_attr__( 'css3-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-cube' => esc_attr__( 'cube', 'advanced-faq-creator-by-category' ),
					'fas fa-cubes' => esc_attr__( 'cubes', 'advanced-faq-creator-by-category' ),
					'fas fa-cut' => esc_attr__( 'cut', 'advanced-faq-creator-by-category' ),
					'fab fa-cuttlefish' => esc_attr__( 'cuttlefish', 'advanced-faq-creator-by-category' ),
					'fab fa-d-and-d' => esc_attr__( 'd-and-d', 'advanced-faq-creator-by-category' ),
					'fab fa-dashcube' => esc_attr__( 'dashcube', 'advanced-faq-creator-by-category' ),
					'fas fa-database' => esc_attr__( 'database', 'advanced-faq-creator-by-category' ),
					'fas fa-deaf' => esc_attr__( 'deaf', 'advanced-faq-creator-by-category' ),
					'fab fa-delicious' => esc_attr__( 'delicious', 'advanced-faq-creator-by-category' ),
					'fab fa-deploydog' => esc_attr__( 'deploydog', 'advanced-faq-creator-by-category' ),
					'fab fa-deskpro' => esc_attr__( 'deskpro', 'advanced-faq-creator-by-category' ),
					'fas fa-desktop' => esc_attr__( 'desktop', 'advanced-faq-creator-by-category' ),
					'fab fa-deviantart' => esc_attr__( 'deviantart', 'advanced-faq-creator-by-category' ),
					'fas fa-diagnoses' => esc_attr__( 'diagnoses', 'advanced-faq-creator-by-category' ),
					'fab fa-digg' => esc_attr__( 'digg', 'advanced-faq-creator-by-category' ),
					'fab fa-digital-ocean' => esc_attr__( 'digital-ocean', 'advanced-faq-creator-by-category' ),
					'fab fa-discord' => esc_attr__( 'discord', 'advanced-faq-creator-by-category' ),
					'fab fa-discourse' => esc_attr__( 'discourse', 'advanced-faq-creator-by-category' ),
					'fas fa-dna' => esc_attr__( 'dna', 'advanced-faq-creator-by-category' ),
					'fab fa-dochub' => esc_attr__( 'dochub', 'advanced-faq-creator-by-category' ),
					'fab fa-docker' => esc_attr__( 'docker', 'advanced-faq-creator-by-category' ),
					'fas fa-dollar-sign' => esc_attr__( 'dollar-sign', 'advanced-faq-creator-by-category' ),
					'fas fa-dolly' => esc_attr__( 'dolly', 'advanced-faq-creator-by-category' ),
					'fas fa-dolly-flatbed' => esc_attr__( 'dolly-flatbed', 'advanced-faq-creator-by-category' ),
					'fas fa-donate' => esc_attr__( 'donate', 'advanced-faq-creator-by-category' ),
					'fas fa-dot-circle' => esc_attr__( 'dot-circle', 'advanced-faq-creator-by-category' ),
					'far fa-dot-circle' => esc_attr__( 'dot-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-dove' => esc_attr__( 'dove', 'advanced-faq-creator-by-category' ),
					'fas fa-download' => esc_attr__( 'download', 'advanced-faq-creator-by-category' ),
					'fab fa-draft2digital' => esc_attr__( 'draft2digital', 'advanced-faq-creator-by-category' ),
					'fab fa-dribbble' => esc_attr__( 'dribbble', 'advanced-faq-creator-by-category' ),
					'fab fa-dribbble-square' => esc_attr__( 'dribbble-square', 'advanced-faq-creator-by-category' ),
					'fab fa-dropbox' => esc_attr__( 'dropbox', 'advanced-faq-creator-by-category' ),
					'fab fa-drupal' => esc_attr__( 'drupal', 'advanced-faq-creator-by-category' ),
					'fab fa-dyalog' => esc_attr__( 'dyalog', 'advanced-faq-creator-by-category' ),
					'fab fa-earlybirds' => esc_attr__( 'earlybirds', 'advanced-faq-creator-by-category' ),
					'fab fa-edge' => esc_attr__( 'edge', 'advanced-faq-creator-by-category' ),
					'fas fa-edit' => esc_attr__( 'edit', 'advanced-faq-creator-by-category' ),
					'far fa-edit' => esc_attr__( 'edit', 'advanced-faq-creator-by-category' ),
					'fas fa-eject' => esc_attr__( 'eject', 'advanced-faq-creator-by-category' ),
					'fab fa-elementor' => esc_attr__( 'elementor', 'advanced-faq-creator-by-category' ),
					'fas fa-ellipsis-h' => esc_attr__( 'ellipsis-h', 'advanced-faq-creator-by-category' ),
					'fas fa-ellipsis-v' => esc_attr__( 'ellipsis-v', 'advanced-faq-creator-by-category' ),
					'fab fa-ember' => esc_attr__( 'ember', 'advanced-faq-creator-by-category' ),
					'fab fa-empire' => esc_attr__( 'empire', 'advanced-faq-creator-by-category' ),
					'fas fa-envelope' => esc_attr__( 'envelope', 'advanced-faq-creator-by-category' ),
					'far fa-envelope' => esc_attr__( 'envelope', 'advanced-faq-creator-by-category' ),
					'fas fa-envelope-open' => esc_attr__( 'envelope-open', 'advanced-faq-creator-by-category' ),
					'far fa-envelope-open' => esc_attr__( 'envelope-open', 'advanced-faq-creator-by-category' ),
					'fas fa-envelope-square' => esc_attr__( 'envelope-square', 'advanced-faq-creator-by-category' ),
					'fab fa-envira' => esc_attr__( 'envira', 'advanced-faq-creator-by-category' ),
					'fas fa-eraser' => esc_attr__( 'eraser', 'advanced-faq-creator-by-category' ),
					'fab fa-erlang' => esc_attr__( 'erlang', 'advanced-faq-creator-by-category' ),
					'fab fa-ethereum' => esc_attr__( 'ethereum', 'advanced-faq-creator-by-category' ),
					'fab fa-etsy' => esc_attr__( 'etsy', 'advanced-faq-creator-by-category' ),
					'fas fa-euro-sign' => esc_attr__( 'euro-sign', 'advanced-faq-creator-by-category' ),
					'fas fa-exchange-alt' => esc_attr__( 'exchange-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-exclamation' => esc_attr__( 'exclamation', 'advanced-faq-creator-by-category' ),
					'fas fa-exclamation-circle' => esc_attr__( 'exclamation-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-exclamation-triangle' => esc_attr__( 'exclamation-triangle', 'advanced-faq-creator-by-category' ),
					'fas fa-expand' => esc_attr__( 'expand', 'advanced-faq-creator-by-category' ),
					'fas fa-expand-arrows-alt' => esc_attr__( 'expand-arrows-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-expeditedssl' => esc_attr__( 'expeditedssl', 'advanced-faq-creator-by-category' ),
					'fas fa-external-link-alt' => esc_attr__( 'external-link-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-external-link-square-alt' => esc_attr__( 'external-link-square-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-eye' => esc_attr__( 'eye', 'advanced-faq-creator-by-category' ),
					'fas fa-eye-dropper' => esc_attr__( 'eye-dropper', 'advanced-faq-creator-by-category' ),
					'fas fa-eye-slash' => esc_attr__( 'eye-slash', 'advanced-faq-creator-by-category' ),
					'far fa-eye-slash' => esc_attr__( 'eye-slash', 'advanced-faq-creator-by-category' ),
					'fab fa-facebook' => esc_attr__( 'facebook', 'advanced-faq-creator-by-category' ),
					'fab fa-facebook-f' => esc_attr__( 'facebook-f', 'advanced-faq-creator-by-category' ),
					'fab fa-facebook-messenger' => esc_attr__( 'facebook-messenger', 'advanced-faq-creator-by-category' ),
					'fab fa-facebook-square' => esc_attr__( 'facebook-square', 'advanced-faq-creator-by-category' ),
					'fas fa-fast-backward' => esc_attr__( 'fast-backward', 'advanced-faq-creator-by-category' ),
					'fas fa-fast-forward' => esc_attr__( 'fast-forward', 'advanced-faq-creator-by-category' ),
					'fas fa-fax' => esc_attr__( 'fax', 'advanced-faq-creator-by-category' ),
					'fas fa-female' => esc_attr__( 'female', 'advanced-faq-creator-by-category' ),
					'fas fa-fighter-jet' => esc_attr__( 'fighter-jet', 'advanced-faq-creator-by-category' ),
					'fas fa-file' => esc_attr__( 'file', 'advanced-faq-creator-by-category' ),
					'far fa-file' => esc_attr__( 'file', 'advanced-faq-creator-by-category' ),
					'fas fa-file-alt' => esc_attr__( 'file-alt', 'advanced-faq-creator-by-category' ),
					'far fa-file-alt' => esc_attr__( 'file-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-file-archive' => esc_attr__( 'file-archive', 'advanced-faq-creator-by-category' ),
					'far fa-file-archive' => esc_attr__( 'file-archive', 'advanced-faq-creator-by-category' ),
					'fas fa-file-audio' => esc_attr__( 'file-audio', 'advanced-faq-creator-by-category' ),
					'far fa-file-audio' => esc_attr__( 'file-audio', 'advanced-faq-creator-by-category' ),
					'fas fa-file-code' => esc_attr__( 'file-code', 'advanced-faq-creator-by-category' ),
					'far fa-file-code' => esc_attr__( 'file-code', 'advanced-faq-creator-by-category' ),
					'fas fa-file-excel' => esc_attr__( 'file-excel', 'advanced-faq-creator-by-category' ),
					'far fa-file-excel' => esc_attr__( 'file-excel', 'advanced-faq-creator-by-category' ),
					'fas fa-file-image' => esc_attr__( 'file-image', 'advanced-faq-creator-by-category' ),
					'far fa-file-image' => esc_attr__( 'file-image', 'advanced-faq-creator-by-category' ),
					'fas fa-file-medical' => esc_attr__( 'file-medical', 'advanced-faq-creator-by-category' ),
					'fas fa-file-medical-alt' => esc_attr__( 'file-medical-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-file-pdf' => esc_attr__( 'file-pdf', 'advanced-faq-creator-by-category' ),
					'far fa-file-pdf' => esc_attr__( 'file-pdf', 'advanced-faq-creator-by-category' ),
					'fas fa-file-powerpoint' => esc_attr__( 'file-powerpoint', 'advanced-faq-creator-by-category' ),
					'far fa-file-powerpoint' => esc_attr__( 'file-powerpoint', 'advanced-faq-creator-by-category' ),
					'fas fa-file-video' => esc_attr__( 'file-video', 'advanced-faq-creator-by-category' ),
					'far fa-file-video' => esc_attr__( 'file-video', 'advanced-faq-creator-by-category' ),
					'fas fa-file-word' => esc_attr__( 'file-word', 'advanced-faq-creator-by-category' ),
					'far fa-file-word' => esc_attr__( 'file-word', 'advanced-faq-creator-by-category' ),
					'fas fa-film' => esc_attr__( 'film', 'advanced-faq-creator-by-category' ),
					'fas fa-filter' => esc_attr__( 'filter', 'advanced-faq-creator-by-category' ),
					'fas fa-fire' => esc_attr__( 'fire', 'advanced-faq-creator-by-category' ),
					'fas fa-fire-extinguisher' => esc_attr__( 'fire-extinguisher', 'advanced-faq-creator-by-category' ),
					'fab fa-firefox' => esc_attr__( 'firefox', 'advanced-faq-creator-by-category' ),
					'fas fa-first-aid' => esc_attr__( 'first-aid', 'advanced-faq-creator-by-category' ),
					'fab fa-first-order' => esc_attr__( 'first-order', 'advanced-faq-creator-by-category' ),
					'fab fa-firstdraft' => esc_attr__( 'firstdraft', 'advanced-faq-creator-by-category' ),
					'fas fa-flag' => esc_attr__( 'flag', 'advanced-faq-creator-by-category' ),
					'far fa-flag' => esc_attr__( 'flag', 'advanced-faq-creator-by-category' ),
					'fas fa-flag-checkered' => esc_attr__( 'flag-checkered', 'advanced-faq-creator-by-category' ),
					'fas fa-flask' => esc_attr__( 'flask', 'advanced-faq-creator-by-category' ),
					'fab fa-flickr' => esc_attr__( 'flickr', 'advanced-faq-creator-by-category' ),
					'fab fa-flipboard' => esc_attr__( 'flipboard', 'advanced-faq-creator-by-category' ),
					'fab fa-fly' => esc_attr__( 'fly', 'advanced-faq-creator-by-category' ),
					'fas fa-folder' => esc_attr__( 'folder', 'advanced-faq-creator-by-category' ),
					'far fa-folder' => esc_attr__( 'folder', 'advanced-faq-creator-by-category' ),
					'fas fa-folder-open' => esc_attr__( 'folder-open', 'advanced-faq-creator-by-category' ),
					'far fa-folder-open' => esc_attr__( 'folder-open', 'advanced-faq-creator-by-category' ),
					'fas fa-font' => esc_attr__( 'font', 'advanced-faq-creator-by-category' ),
					'fab fa-font-awesome' => esc_attr__( 'font-awesome', 'advanced-faq-creator-by-category' ),
					'fab fa-font-awesome-alt' => esc_attr__( 'font-awesome-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-font-awesome-flag' => esc_attr__( 'font-awesome-flag', 'advanced-faq-creator-by-category' ),
					'fab fa-fonticons' => esc_attr__( 'fonticons', 'advanced-faq-creator-by-category' ),
					'fab fa-fonticons-fi' => esc_attr__( 'fonticons-fi', 'advanced-faq-creator-by-category' ),
					'fas fa-football-ball' => esc_attr__( 'football-ball', 'advanced-faq-creator-by-category' ),
					'fab fa-fort-awesome' => esc_attr__( 'fort-awesome', 'advanced-faq-creator-by-category' ),
					'fab fa-fort-awesome-alt' => esc_attr__( 'fort-awesome-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-forumbee' => esc_attr__( 'forumbee', 'advanced-faq-creator-by-category' ),
					'fas fa-forward' => esc_attr__( 'forward', 'advanced-faq-creator-by-category' ),
					'fab fa-foursquare' => esc_attr__( 'foursquare', 'advanced-faq-creator-by-category' ),
					'fab fa-free-code-camp' => esc_attr__( 'free-code-camp', 'advanced-faq-creator-by-category' ),
					'fab fa-freebsd' => esc_attr__( 'freebsd', 'advanced-faq-creator-by-category' ),
					'fas fa-frown' => esc_attr__( 'frown', 'advanced-faq-creator-by-category' ),
					'far fa-frown' => esc_attr__( 'frown', 'advanced-faq-creator-by-category' ),
					'fas fa-futbol' => esc_attr__( 'futbol', 'advanced-faq-creator-by-category' ),
					'far fa-futbol' => esc_attr__( 'futbol', 'advanced-faq-creator-by-category' ),
					'fas fa-gamepad' => esc_attr__( 'gamepad', 'advanced-faq-creator-by-category' ),
					'fas fa-gavel' => esc_attr__( 'gavel', 'advanced-faq-creator-by-category' ),
					'fas fa-gem' => esc_attr__( 'gem', 'advanced-faq-creator-by-category' ),
					'far fa-gem' => esc_attr__( 'gem', 'advanced-faq-creator-by-category' ),
					'fas fa-genderless' => esc_attr__( 'genderless', 'advanced-faq-creator-by-category' ),
					'fab fa-get-pocket' => esc_attr__( 'get-pocket', 'advanced-faq-creator-by-category' ),
					'fab fa-gg' => esc_attr__( 'gg', 'advanced-faq-creator-by-category' ),
					'fab fa-gg-circle' => esc_attr__( 'gg-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-gift' => esc_attr__( 'gift', 'advanced-faq-creator-by-category' ),
					'fab fa-git' => esc_attr__( 'git', 'advanced-faq-creator-by-category' ),
					'fab fa-git-square' => esc_attr__( 'git-square', 'advanced-faq-creator-by-category' ),
					'fab fa-github' => esc_attr__( 'github', 'advanced-faq-creator-by-category' ),
					'fab fa-github-alt' => esc_attr__( 'github-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-github-square' => esc_attr__( 'github-square', 'advanced-faq-creator-by-category' ),
					'fab fa-gitkraken' => esc_attr__( 'gitkraken', 'advanced-faq-creator-by-category' ),
					'fab fa-gitlab' => esc_attr__( 'gitlab', 'advanced-faq-creator-by-category' ),
					'fab fa-gitter' => esc_attr__( 'gitter', 'advanced-faq-creator-by-category' ),
					'fas fa-glass-martini' => esc_attr__( 'glass-martini', 'advanced-faq-creator-by-category' ),
					'fab fa-glide' => esc_attr__( 'glide', 'advanced-faq-creator-by-category' ),
					'fab fa-glide-g' => esc_attr__( 'glide-g', 'advanced-faq-creator-by-category' ),
					'fas fa-globe' => esc_attr__( 'globe', 'advanced-faq-creator-by-category' ),
					'fab fa-gofore' => esc_attr__( 'gofore', 'advanced-faq-creator-by-category' ),
					'fas fa-golf-ball' => esc_attr__( 'golf-ball', 'advanced-faq-creator-by-category' ),
					'fab fa-goodreads' => esc_attr__( 'goodreads', 'advanced-faq-creator-by-category' ),
					'fab fa-goodreads-g' => esc_attr__( 'goodreads-g', 'advanced-faq-creator-by-category' ),
					'fab fa-google' => esc_attr__( 'google', 'advanced-faq-creator-by-category' ),
					'fab fa-google-drive' => esc_attr__( 'google-drive', 'advanced-faq-creator-by-category' ),
					'fab fa-google-play' => esc_attr__( 'google-play', 'advanced-faq-creator-by-category' ),
					'fab fa-google-plus' => esc_attr__( 'google-plus', 'advanced-faq-creator-by-category' ),
					'fab fa-google-plus-g' => esc_attr__( 'google-plus-g', 'advanced-faq-creator-by-category' ),
					'fab fa-google-plus-square' => esc_attr__( 'google-plus-square', 'advanced-faq-creator-by-category' ),
					'fab fa-google-wallet' => esc_attr__( 'google-wallet', 'advanced-faq-creator-by-category' ),
					'fas fa-graduation-cap' => esc_attr__( 'graduation-cap', 'advanced-faq-creator-by-category' ),
					'fab fa-gratipay' => esc_attr__( 'gratipay', 'advanced-faq-creator-by-category' ),
					'fab fa-grav' => esc_attr__( 'grav', 'advanced-faq-creator-by-category' ),
					'fab fa-gripfire' => esc_attr__( 'gripfire', 'advanced-faq-creator-by-category' ),
					'fab fa-grunt' => esc_attr__( 'grunt', 'advanced-faq-creator-by-category' ),
					'fab fa-gulp' => esc_attr__( 'gulp', 'advanced-faq-creator-by-category' ),
					'fas fa-h-square' => esc_attr__( 'h-square', 'advanced-faq-creator-by-category' ),
					'fab fa-hacker-news' => esc_attr__( 'hacker-news', 'advanced-faq-creator-by-category' ),
					'fab fa-hacker-news-square' => esc_attr__( 'hacker-news-square', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-holding' => esc_attr__( 'hand-holding', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-holding-heart' => esc_attr__( 'hand-holding-heart', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-holding-usd' => esc_attr__( 'hand-holding-usd', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-lizard' => esc_attr__( 'hand-lizard', 'advanced-faq-creator-by-category' ),
					'far fa-hand-lizard' => esc_attr__( 'hand-lizard', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-paper' => esc_attr__( 'hand-paper', 'advanced-faq-creator-by-category' ),
					'far fa-hand-paper' => esc_attr__( 'hand-paper', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-peace' => esc_attr__( 'hand-peace', 'advanced-faq-creator-by-category' ),
					'far fa-hand-peace' => esc_attr__( 'hand-peace', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-point-down' => esc_attr__( 'hand-point-down', 'advanced-faq-creator-by-category' ),
					'far fa-hand-point-down' => esc_attr__( 'hand-point-down', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-point-left' => esc_attr__( 'hand-point-left', 'advanced-faq-creator-by-category' ),
					'far fa-hand-point-left' => esc_attr__( 'hand-point-left', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-point-right' => esc_attr__( 'hand-point-right', 'advanced-faq-creator-by-category' ),
					'far fa-hand-point-right' => esc_attr__( 'hand-point-right', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-point-up' => esc_attr__( 'hand-point-up', 'advanced-faq-creator-by-category' ),
					'far fa-hand-point-up' => esc_attr__( 'hand-point-up', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-pointer' => esc_attr__( 'hand-pointer', 'advanced-faq-creator-by-category' ),
					'far fa-hand-pointer' => esc_attr__( 'hand-pointer', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-rock' => esc_attr__( 'hand-rock', 'advanced-faq-creator-by-category' ),
					'far fa-hand-rock' => esc_attr__( 'hand-rock', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-scissors' => esc_attr__( 'hand-scissors', 'advanced-faq-creator-by-category' ),
					'far fa-hand-scissors' => esc_attr__( 'hand-scissors', 'advanced-faq-creator-by-category' ),
					'fas fa-hand-spock' => esc_attr__( 'hand-spock', 'advanced-faq-creator-by-category' ),
					'far fa-hand-spock' => esc_attr__( 'hand-spock', 'advanced-faq-creator-by-category' ),
					'fas fa-hands' => esc_attr__( 'hands', 'advanced-faq-creator-by-category' ),
					'fas fa-hands-helping' => esc_attr__( 'hands-helping', 'advanced-faq-creator-by-category' ),
					'fas fa-handshake' => esc_attr__( 'handshake', 'advanced-faq-creator-by-category' ),
					'far fa-handshake' => esc_attr__( 'handshake', 'advanced-faq-creator-by-category' ),
					'fas fa-hashtag' => esc_attr__( 'hashtag', 'advanced-faq-creator-by-category' ),
					'fas fa-hdd' => esc_attr__( 'hdd', 'advanced-faq-creator-by-category' ),
					'far fa-hdd' => esc_attr__( 'hdd', 'advanced-faq-creator-by-category' ),
					'fas fa-heading' => esc_attr__( 'heading', 'advanced-faq-creator-by-category' ),
					'fas fa-headphones' => esc_attr__( 'headphones', 'advanced-faq-creator-by-category' ),
					'fas fa-heart' => esc_attr__( 'heart', 'advanced-faq-creator-by-category' ),
					'far fa-heart' => esc_attr__( 'heart', 'advanced-faq-creator-by-category' ),
					'fas fa-heartbeat' => esc_attr__( 'heartbeat', 'advanced-faq-creator-by-category' ),
					'fab fa-hips' => esc_attr__( 'hips', 'advanced-faq-creator-by-category' ),
					'fab fa-hire-a-helper' => esc_attr__( 'hire-a-helper', 'advanced-faq-creator-by-category' ),
					'fas fa-history' => esc_attr__( 'history', 'advanced-faq-creator-by-category' ),
					'fas fa-hockey-puck' => esc_attr__( 'hockey-puck', 'advanced-faq-creator-by-category' ),
					'fas fa-home' => esc_attr__( 'home', 'advanced-faq-creator-by-category' ),
					'fab fa-hooli' => esc_attr__( 'hooli', 'advanced-faq-creator-by-category' ),
					'fas fa-hospital' => esc_attr__( 'hospital', 'advanced-faq-creator-by-category' ),
					'far fa-hospital' => esc_attr__( 'hospital', 'advanced-faq-creator-by-category' ),
					'fas fa-hospital-alt' => esc_attr__( 'hospital-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-hospital-symbol' => esc_attr__( 'hospital-symbol', 'advanced-faq-creator-by-category' ),
					'fab fa-hotjar' => esc_attr__( 'hotjar', 'advanced-faq-creator-by-category' ),
					'fas fa-hourglass' => esc_attr__( 'hourglass', 'advanced-faq-creator-by-category' ),
					'far fa-hourglass' => esc_attr__( 'hourglass', 'advanced-faq-creator-by-category' ),
					'fas fa-hourglass-end' => esc_attr__( 'hourglass-end', 'advanced-faq-creator-by-category' ),
					'fas fa-hourglass-half' => esc_attr__( 'hourglass-half', 'advanced-faq-creator-by-category' ),
					'fas fa-hourglass-start' => esc_attr__( 'hourglass-start', 'advanced-faq-creator-by-category' ),
					'fab fa-houzz' => esc_attr__( 'houzz', 'advanced-faq-creator-by-category' ),
					'fab fa-html5' => esc_attr__( 'html5', 'advanced-faq-creator-by-category' ),
					'fab fa-hubspot' => esc_attr__( 'hubspot', 'advanced-faq-creator-by-category' ),
					'fas fa-i-cursor' => esc_attr__( 'i-cursor', 'advanced-faq-creator-by-category' ),
					'fas fa-id-badge' => esc_attr__( 'id-badge', 'advanced-faq-creator-by-category' ),
					'far fa-id-badge' => esc_attr__( 'id-badge', 'advanced-faq-creator-by-category' ),
					'fas fa-id-card' => esc_attr__( 'id-card', 'advanced-faq-creator-by-category' ),
					'far fa-id-card' => esc_attr__( 'id-card', 'advanced-faq-creator-by-category' ),
					'fas fa-id-card-alt' => esc_attr__( 'id-card-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-image' => esc_attr__( 'image', 'advanced-faq-creator-by-category' ),
					'far fa-image' => esc_attr__( 'image', 'advanced-faq-creator-by-category' ),
					'fas fa-images' => esc_attr__( 'images', 'advanced-faq-creator-by-category' ),
					'far fa-images' => esc_attr__( 'images', 'advanced-faq-creator-by-category' ),
					'fab fa-imdb' => esc_attr__( 'imdb', 'advanced-faq-creator-by-category' ),
					'fas fa-inbox' => esc_attr__( 'inbox', 'advanced-faq-creator-by-category' ),
					'fas fa-indent' => esc_attr__( 'indent', 'advanced-faq-creator-by-category' ),
					'fas fa-industry' => esc_attr__( 'industry', 'advanced-faq-creator-by-category' ),
					'fas fa-info' => esc_attr__( 'info', 'advanced-faq-creator-by-category' ),
					'fas fa-info-circle' => esc_attr__( 'info-circle', 'advanced-faq-creator-by-category' ),
					'fab fa-instagram' => esc_attr__( 'instagram', 'advanced-faq-creator-by-category' ),
					'fab fa-internet-explorer' => esc_attr__( 'internet-explorer', 'advanced-faq-creator-by-category' ),
					'fab fa-ioxhost' => esc_attr__( 'ioxhost', 'advanced-faq-creator-by-category' ),
					'fas fa-italic' => esc_attr__( 'italic', 'advanced-faq-creator-by-category' ),
					'fab fa-itunes' => esc_attr__( 'itunes', 'advanced-faq-creator-by-category' ),
					'fab fa-itunes-note' => esc_attr__( 'itunes-note', 'advanced-faq-creator-by-category' ),
					'fab fa-java' => esc_attr__( 'java', 'advanced-faq-creator-by-category' ),
					'fab fa-jenkins' => esc_attr__( 'jenkins', 'advanced-faq-creator-by-category' ),
					'fab fa-joget' => esc_attr__( 'joget', 'advanced-faq-creator-by-category' ),
					'fab fa-joomla' => esc_attr__( 'joomla', 'advanced-faq-creator-by-category' ),
					'fab fa-js' => esc_attr__( 'js', 'advanced-faq-creator-by-category' ),
					'fab fa-js-square' => esc_attr__( 'js-square', 'advanced-faq-creator-by-category' ),
					'fab fa-jsfiddle' => esc_attr__( 'jsfiddle', 'advanced-faq-creator-by-category' ),
					'fas fa-key' => esc_attr__( 'key', 'advanced-faq-creator-by-category' ),
					'fas fa-keyboard' => esc_attr__( 'keyboard', 'advanced-faq-creator-by-category' ),
					'far fa-keyboard' => esc_attr__( 'keyboard', 'advanced-faq-creator-by-category' ),
					'fab fa-keycdn' => esc_attr__( 'keycdn', 'advanced-faq-creator-by-category' ),
					'fab fa-kickstarter' => esc_attr__( 'kickstarter', 'advanced-faq-creator-by-category' ),
					'fab fa-kickstarter-k' => esc_attr__( 'kickstarter-k', 'advanced-faq-creator-by-category' ),
					'fab fa-korvue' => esc_attr__( 'korvue', 'advanced-faq-creator-by-category' ),
					'fas fa-language' => esc_attr__( 'language', 'advanced-faq-creator-by-category' ),
					'fas fa-laptop' => esc_attr__( 'laptop', 'advanced-faq-creator-by-category' ),
					'fab fa-laravel' => esc_attr__( 'laravel', 'advanced-faq-creator-by-category' ),
					'fab fa-lastfm' => esc_attr__( 'lastfm', 'advanced-faq-creator-by-category' ),
					'fab fa-lastfm-square' => esc_attr__( 'lastfm-square', 'advanced-faq-creator-by-category' ),
					'fas fa-leaf' => esc_attr__( 'leaf', 'advanced-faq-creator-by-category' ),
					'fab fa-leanpub' => esc_attr__( 'leanpub', 'advanced-faq-creator-by-category' ),
					'fas fa-lemon' => esc_attr__( 'lemon', 'advanced-faq-creator-by-category' ),
					'far fa-lemon' => esc_attr__( 'lemon', 'advanced-faq-creator-by-category' ),
					'fab fa-less' => esc_attr__( 'less', 'advanced-faq-creator-by-category' ),
					'fas fa-level-down-alt' => esc_attr__( 'level-down-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-level-up-alt' => esc_attr__( 'level-up-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-life-ring' => esc_attr__( 'life-ring', 'advanced-faq-creator-by-category' ),
					'far fa-life-ring' => esc_attr__( 'life-ring', 'advanced-faq-creator-by-category' ),
					'fas fa-lightbulb' => esc_attr__( 'lightbulb', 'advanced-faq-creator-by-category' ),
					'far fa-lightbulb' => esc_attr__( 'lightbulb', 'advanced-faq-creator-by-category' ),
					'fab fa-line' => esc_attr__( 'line', 'advanced-faq-creator-by-category' ),
					'fas fa-link' => esc_attr__( 'link', 'advanced-faq-creator-by-category' ),
					'fab fa-linkedin' => esc_attr__( 'linkedin', 'advanced-faq-creator-by-category' ),
					'fab fa-linkedin-in' => esc_attr__( 'linkedin-in', 'advanced-faq-creator-by-category' ),
					'fab fa-linode' => esc_attr__( 'linode', 'advanced-faq-creator-by-category' ),
					'fab fa-linux' => esc_attr__( 'linux', 'advanced-faq-creator-by-category' ),
					'fas fa-lira-sign' => esc_attr__( 'lira-sign', 'advanced-faq-creator-by-category' ),
					'fas fa-list' => esc_attr__( 'list', 'advanced-faq-creator-by-category' ),
					'fas fa-list-alt' => esc_attr__( 'list-alt', 'advanced-faq-creator-by-category' ),
					'far fa-list-alt' => esc_attr__( 'list-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-list-ol' => esc_attr__( 'list-ol', 'advanced-faq-creator-by-category' ),
					'fas fa-list-ul' => esc_attr__( 'list-ul', 'advanced-faq-creator-by-category' ),
					'fas fa-location-arrow' => esc_attr__( 'location-arrow', 'advanced-faq-creator-by-category' ),
					'fas fa-lock' => esc_attr__( 'lock', 'advanced-faq-creator-by-category' ),
					'fas fa-lock-open' => esc_attr__( 'lock-open', 'advanced-faq-creator-by-category' ),
					'fas fa-long-arrow-alt-down' => esc_attr__( 'long-arrow-alt-down', 'advanced-faq-creator-by-category' ),
					'fas fa-long-arrow-alt-left' => esc_attr__( 'long-arrow-alt-left', 'advanced-faq-creator-by-category' ),
					'fas fa-long-arrow-alt-right' => esc_attr__( 'long-arrow-alt-right', 'advanced-faq-creator-by-category' ),
					'fas fa-long-arrow-alt-up' => esc_attr__( 'long-arrow-alt-up', 'advanced-faq-creator-by-category' ),
					'fas fa-low-vision' => esc_attr__( 'low-vision', 'advanced-faq-creator-by-category' ),
					'fab fa-lyft' => esc_attr__( 'lyft', 'advanced-faq-creator-by-category' ),
					'fab fa-magento' => esc_attr__( 'magento', 'advanced-faq-creator-by-category' ),
					'fas fa-magic' => esc_attr__( 'magic', 'advanced-faq-creator-by-category' ),
					'fas fa-magnet' => esc_attr__( 'magnet', 'advanced-faq-creator-by-category' ),
					'fas fa-male' => esc_attr__( 'male', 'advanced-faq-creator-by-category' ),
					'fas fa-map' => esc_attr__( 'map', 'advanced-faq-creator-by-category' ),
					'far fa-map' => esc_attr__( 'map', 'advanced-faq-creator-by-category' ),
					'fas fa-map-marker' => esc_attr__( 'map-marker', 'advanced-faq-creator-by-category' ),
					'fas fa-map-marker-alt' => esc_attr__( 'map-marker-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-map-pin' => esc_attr__( 'map-pin', 'advanced-faq-creator-by-category' ),
					'fas fa-map-signs' => esc_attr__( 'map-signs', 'advanced-faq-creator-by-category' ),
					'fas fa-mars' => esc_attr__( 'mars', 'advanced-faq-creator-by-category' ),
					'fas fa-mars-double' => esc_attr__( 'mars-double', 'advanced-faq-creator-by-category' ),
					'fas fa-mars-stroke' => esc_attr__( 'mars-stroke', 'advanced-faq-creator-by-category' ),
					'fas fa-mars-stroke-h' => esc_attr__( 'mars-stroke-h', 'advanced-faq-creator-by-category' ),
					'fas fa-mars-stroke-v' => esc_attr__( 'mars-stroke-v', 'advanced-faq-creator-by-category' ),
					'fab fa-maxcdn' => esc_attr__( 'maxcdn', 'advanced-faq-creator-by-category' ),
					'fab fa-medapps' => esc_attr__( 'medapps', 'advanced-faq-creator-by-category' ),
					'fab fa-medium' => esc_attr__( 'medium', 'advanced-faq-creator-by-category' ),
					'fab fa-medium-m' => esc_attr__( 'medium-m', 'advanced-faq-creator-by-category' ),
					'fas fa-medkit' => esc_attr__( 'medkit', 'advanced-faq-creator-by-category' ),
					'fab fa-medrt' => esc_attr__( 'medrt', 'advanced-faq-creator-by-category' ),
					'fab fa-meetup' => esc_attr__( 'meetup', 'advanced-faq-creator-by-category' ),
					'fas fa-meh' => esc_attr__( 'meh', 'advanced-faq-creator-by-category' ),
					'far fa-meh' => esc_attr__( 'meh', 'advanced-faq-creator-by-category' ),
					'fas fa-mercury' => esc_attr__( 'mercury', 'advanced-faq-creator-by-category' ),
					'fas fa-microchip' => esc_attr__( 'microchip', 'advanced-faq-creator-by-category' ),
					'fas fa-microphone' => esc_attr__( 'microphone', 'advanced-faq-creator-by-category' ),
					'fas fa-microphone-slash' => esc_attr__( 'microphone-slash', 'advanced-faq-creator-by-category' ),
					'fab fa-microsoft' => esc_attr__( 'microsoft', 'advanced-faq-creator-by-category' ),
					'fas fa-minus' => esc_attr__( 'minus', 'advanced-faq-creator-by-category' ),
					'fas fa-minus-circle' => esc_attr__( 'minus-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-minus-square' => esc_attr__( 'minus-square', 'advanced-faq-creator-by-category' ),
					'far fa-minus-square' => esc_attr__( 'minus-square', 'advanced-faq-creator-by-category' ),
					'fab fa-mix' => esc_attr__( 'mix', 'advanced-faq-creator-by-category' ),
					'fab fa-mixcloud' => esc_attr__( 'mixcloud', 'advanced-faq-creator-by-category' ),
					'fab fa-mizuni' => esc_attr__( 'mizuni', 'advanced-faq-creator-by-category' ),
					'fas fa-mobile' => esc_attr__( 'mobile', 'advanced-faq-creator-by-category' ),
					'fas fa-mobile-alt' => esc_attr__( 'mobile-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-modx' => esc_attr__( 'modx', 'advanced-faq-creator-by-category' ),
					'fab fa-monero' => esc_attr__( 'monero', 'advanced-faq-creator-by-category' ),
					'fas fa-money-bill-alt' => esc_attr__( 'money-bill-alt', 'advanced-faq-creator-by-category' ),
					'far fa-money-bill-alt' => esc_attr__( 'money-bill-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-moon' => esc_attr__( 'moon', 'advanced-faq-creator-by-category' ),
					'far fa-moon' => esc_attr__( 'moon', 'advanced-faq-creator-by-category' ),
					'fas fa-motorcycle' => esc_attr__( 'motorcycle', 'advanced-faq-creator-by-category' ),
					'fas fa-mouse-pointer' => esc_attr__( 'mouse-pointer', 'advanced-faq-creator-by-category' ),
					'fas fa-music' => esc_attr__( 'music', 'advanced-faq-creator-by-category' ),
					'fab fa-napster' => esc_attr__( 'napster', 'advanced-faq-creator-by-category' ),
					'fas fa-neuter' => esc_attr__( 'neuter', 'advanced-faq-creator-by-category' ),
					'fas fa-newspaper' => esc_attr__( 'newspaper', 'advanced-faq-creator-by-category' ),
					'far fa-newspaper' => esc_attr__( 'newspaper', 'advanced-faq-creator-by-category' ),
					'fab fa-nintendo-switch' => esc_attr__( 'nintendo-switch', 'advanced-faq-creator-by-category' ),
					'fab fa-node' => esc_attr__( 'node', 'advanced-faq-creator-by-category' ),
					'fab fa-node-js' => esc_attr__( 'node-js', 'advanced-faq-creator-by-category' ),
					'fas fa-notes-medical' => esc_attr__( 'notes-medical', 'advanced-faq-creator-by-category' ),
					'fab fa-npm' => esc_attr__( 'npm', 'advanced-faq-creator-by-category' ),
					'fab fa-ns8' => esc_attr__( 'ns8', 'advanced-faq-creator-by-category' ),
					'fab fa-nutritionix' => esc_attr__( 'nutritionix', 'advanced-faq-creator-by-category' ),
					'fas fa-object-group' => esc_attr__( 'object-group', 'advanced-faq-creator-by-category' ),
					'far fa-object-group' => esc_attr__( 'object-group', 'advanced-faq-creator-by-category' ),
					'fas fa-object-ungroup' => esc_attr__( 'object-ungroup', 'advanced-faq-creator-by-category' ),
					'far fa-object-ungroup' => esc_attr__( 'object-ungroup', 'advanced-faq-creator-by-category' ),
					'fab fa-odnoklassniki' => esc_attr__( 'odnoklassniki', 'advanced-faq-creator-by-category' ),
					'fab fa-odnoklassniki-square' => esc_attr__( 'odnoklassniki-square', 'advanced-faq-creator-by-category' ),
					'fab fa-opencart' => esc_attr__( 'opencart', 'advanced-faq-creator-by-category' ),
					'fab fa-openid' => esc_attr__( 'openid', 'advanced-faq-creator-by-category' ),
					'fab fa-opera' => esc_attr__( 'opera', 'advanced-faq-creator-by-category' ),
					'fab fa-optin-monster' => esc_attr__( 'optin-monster', 'advanced-faq-creator-by-category' ),
					'fab fa-osi' => esc_attr__( 'osi', 'advanced-faq-creator-by-category' ),
					'fas fa-outdent' => esc_attr__( 'outdent', 'advanced-faq-creator-by-category' ),
					'fab fa-page4' => esc_attr__( 'page4', 'advanced-faq-creator-by-category' ),
					'fab fa-pagelines' => esc_attr__( 'pagelines', 'advanced-faq-creator-by-category' ),
					'fas fa-paint-brush' => esc_attr__( 'paint-brush', 'advanced-faq-creator-by-category' ),
					'fab fa-palfed' => esc_attr__( 'palfed', 'advanced-faq-creator-by-category' ),
					'fas fa-pallet' => esc_attr__( 'pallet', 'advanced-faq-creator-by-category' ),
					'fas fa-paper-plane' => esc_attr__( 'paper-plane', 'advanced-faq-creator-by-category' ),
					'far fa-paper-plane' => esc_attr__( 'paper-plane', 'advanced-faq-creator-by-category' ),
					'fas fa-paperclip' => esc_attr__( 'paperclip', 'advanced-faq-creator-by-category' ),
					'fas fa-parachute-box' => esc_attr__( 'parachute-box', 'advanced-faq-creator-by-category' ),
					'fas fa-paragraph' => esc_attr__( 'paragraph', 'advanced-faq-creator-by-category' ),
					'fas fa-paste' => esc_attr__( 'paste', 'advanced-faq-creator-by-category' ),
					'fab fa-patreon' => esc_attr__( 'patreon', 'advanced-faq-creator-by-category' ),
					'fas fa-pause' => esc_attr__( 'pause', 'advanced-faq-creator-by-category' ),
					'fas fa-pause-circle' => esc_attr__( 'pause-circle', 'advanced-faq-creator-by-category' ),
					'far fa-pause-circle' => esc_attr__( 'pause-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-paw' => esc_attr__( 'paw', 'advanced-faq-creator-by-category' ),
					'fab fa-paypal' => esc_attr__( 'paypal', 'advanced-faq-creator-by-category' ),
					'fas fa-pen-square' => esc_attr__( 'pen-square', 'advanced-faq-creator-by-category' ),
					'fas fa-pencil-alt' => esc_attr__( 'pencil-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-people-carry' => esc_attr__( 'people-carry', 'advanced-faq-creator-by-category' ),
					'fas fa-percent' => esc_attr__( 'percent', 'advanced-faq-creator-by-category' ),
					'fab fa-periscope' => esc_attr__( 'periscope', 'advanced-faq-creator-by-category' ),
					'fab fa-phabricator' => esc_attr__( 'phabricator', 'advanced-faq-creator-by-category' ),
					'fab fa-phoenix-framework' => esc_attr__( 'phoenix-framework', 'advanced-faq-creator-by-category' ),
					'fas fa-phone' => esc_attr__( 'phone', 'advanced-faq-creator-by-category' ),
					'fas fa-phone-slash' => esc_attr__( 'phone-slash', 'advanced-faq-creator-by-category' ),
					'fas fa-phone-square' => esc_attr__( 'phone-square', 'advanced-faq-creator-by-category' ),
					'fas fa-phone-volume' => esc_attr__( 'phone-volume', 'advanced-faq-creator-by-category' ),
					'fab fa-php' => esc_attr__( 'php', 'advanced-faq-creator-by-category' ),
					'fab fa-pied-piper' => esc_attr__( 'pied-piper', 'advanced-faq-creator-by-category' ),
					'fab fa-pied-piper-alt' => esc_attr__( 'pied-piper-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-pied-piper-hat' => esc_attr__( 'pied-piper-hat', 'advanced-faq-creator-by-category' ),
					'fab fa-pied-piper-pp' => esc_attr__( 'pied-piper-pp', 'advanced-faq-creator-by-category' ),
					'fas fa-piggy-bank' => esc_attr__( 'piggy-bank', 'advanced-faq-creator-by-category' ),
					'fas fa-pills' => esc_attr__( 'pills', 'advanced-faq-creator-by-category' ),
					'fab fa-pinterest' => esc_attr__( 'pinterest', 'advanced-faq-creator-by-category' ),
					'fab fa-pinterest-p' => esc_attr__( 'pinterest-p', 'advanced-faq-creator-by-category' ),
					'fab fa-pinterest-square' => esc_attr__( 'pinterest-square', 'advanced-faq-creator-by-category' ),
					'fas fa-plane' => esc_attr__( 'plane', 'advanced-faq-creator-by-category' ),
					'fas fa-play' => esc_attr__( 'play', 'advanced-faq-creator-by-category' ),
					'fas fa-play-circle' => esc_attr__( 'play-circle', 'advanced-faq-creator-by-category' ),
					'far fa-play-circle' => esc_attr__( 'play-circle', 'advanced-faq-creator-by-category' ),
					'fab fa-playstation' => esc_attr__( 'playstation', 'advanced-faq-creator-by-category' ),
					'fas fa-plug' => esc_attr__( 'plug', 'advanced-faq-creator-by-category' ),
					'fas fa-plus' => esc_attr__( 'plus', 'advanced-faq-creator-by-category' ),
					'fas fa-plus-circle' => esc_attr__( 'plus-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-plus-square' => esc_attr__( 'plus-square', 'advanced-faq-creator-by-category' ),
					'far fa-plus-square' => esc_attr__( 'plus-square', 'advanced-faq-creator-by-category' ),
					'fas fa-podcast' => esc_attr__( 'podcast', 'advanced-faq-creator-by-category' ),
					'fas fa-poo' => esc_attr__( 'poo', 'advanced-faq-creator-by-category' ),
					'fas fa-pound-sign' => esc_attr__( 'pound-sign', 'advanced-faq-creator-by-category' ),
					'fas fa-power-off' => esc_attr__( 'power-off', 'advanced-faq-creator-by-category' ),
					'fas fa-prescription-bottle' => esc_attr__( 'prescription-bottle', 'advanced-faq-creator-by-category' ),
					'fas fa-prescription-bottle-alt' => esc_attr__( 'prescription-bottle-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-print' => esc_attr__( 'print', 'advanced-faq-creator-by-category' ),
					'fas fa-procedures' => esc_attr__( 'procedures', 'advanced-faq-creator-by-category' ),
					'fab fa-product-hunt' => esc_attr__( 'product-hunt', 'advanced-faq-creator-by-category' ),
					'fab fa-pushed' => esc_attr__( 'pushed', 'advanced-faq-creator-by-category' ),
					'fas fa-puzzle-piece' => esc_attr__( 'puzzle-piece', 'advanced-faq-creator-by-category' ),
					'fab fa-python' => esc_attr__( 'python', 'advanced-faq-creator-by-category' ),
					'fab fa-qq' => esc_attr__( 'qq', 'advanced-faq-creator-by-category' ),
					'fas fa-qrcode' => esc_attr__( 'qrcode', 'advanced-faq-creator-by-category' ),
					'fas fa-question' => esc_attr__( 'question', 'advanced-faq-creator-by-category' ),
					'fas fa-question-circle' => esc_attr__( 'question-circle', 'advanced-faq-creator-by-category' ),
					'far fa-question-circle' => esc_attr__( 'question-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-quidditch' => esc_attr__( 'quidditch', 'advanced-faq-creator-by-category' ),
					'fab fa-quinscape' => esc_attr__( 'quinscape', 'advanced-faq-creator-by-category' ),
					'fab fa-quora' => esc_attr__( 'quora', 'advanced-faq-creator-by-category' ),
					'fas fa-quote-left' => esc_attr__( 'quote-left', 'advanced-faq-creator-by-category' ),
					'fas fa-quote-right' => esc_attr__( 'quote-right', 'advanced-faq-creator-by-category' ),
					'fas fa-random' => esc_attr__( 'random', 'advanced-faq-creator-by-category' ),
					'fab fa-ravelry' => esc_attr__( 'ravelry', 'advanced-faq-creator-by-category' ),
					'fab fa-react' => esc_attr__( 'react', 'advanced-faq-creator-by-category' ),
					'fab fa-readme' => esc_attr__( 'readme', 'advanced-faq-creator-by-category' ),
					'fab fa-rebel' => esc_attr__( 'rebel', 'advanced-faq-creator-by-category' ),
					'fas fa-recycle' => esc_attr__( 'recycle', 'advanced-faq-creator-by-category' ),
					'fab fa-red-river' => esc_attr__( 'red-river', 'advanced-faq-creator-by-category' ),
					'fab fa-reddit' => esc_attr__( 'reddit', 'advanced-faq-creator-by-category' ),
					'fab fa-reddit-alien' => esc_attr__( 'reddit-alien', 'advanced-faq-creator-by-category' ),
					'fab fa-reddit-square' => esc_attr__( 'reddit-square', 'advanced-faq-creator-by-category' ),
					'fas fa-redo' => esc_attr__( 'redo', 'advanced-faq-creator-by-category' ),
					'fas fa-redo-alt' => esc_attr__( 'redo-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-registered' => esc_attr__( 'registered', 'advanced-faq-creator-by-category' ),
					'far fa-registered' => esc_attr__( 'registered', 'advanced-faq-creator-by-category' ),
					'fab fa-rendact' => esc_attr__( 'rendact', 'advanced-faq-creator-by-category' ),
					'fab fa-renren' => esc_attr__( 'renren', 'advanced-faq-creator-by-category' ),
					'fas fa-reply' => esc_attr__( 'reply', 'advanced-faq-creator-by-category' ),
					'fas fa-reply-all' => esc_attr__( 'reply-all', 'advanced-faq-creator-by-category' ),
					'fab fa-replyd' => esc_attr__( 'replyd', 'advanced-faq-creator-by-category' ),
					'fab fa-resolving' => esc_attr__( 'resolving', 'advanced-faq-creator-by-category' ),
					'fas fa-retweet' => esc_attr__( 'retweet', 'advanced-faq-creator-by-category' ),
					'fas fa-ribbon' => esc_attr__( 'ribbon', 'advanced-faq-creator-by-category' ),
					'fas fa-road' => esc_attr__( 'road', 'advanced-faq-creator-by-category' ),
					'fas fa-rocket' => esc_attr__( 'rocket', 'advanced-faq-creator-by-category' ),
					'fab fa-rocketchat' => esc_attr__( 'rocketchat', 'advanced-faq-creator-by-category' ),
					'fab fa-rockrms' => esc_attr__( 'rockrms', 'advanced-faq-creator-by-category' ),
					'fas fa-rss' => esc_attr__( 'rss', 'advanced-faq-creator-by-category' ),
					'fas fa-rss-square' => esc_attr__( 'rss-square', 'advanced-faq-creator-by-category' ),
					'fas fa-ruble-sign' => esc_attr__( 'ruble-sign', 'advanced-faq-creator-by-category' ),
					'fas fa-rupee-sign' => esc_attr__( 'rupee-sign', 'advanced-faq-creator-by-category' ),
					'fab fa-safari' => esc_attr__( 'safari', 'advanced-faq-creator-by-category' ),
					'fab fa-sass' => esc_attr__( 'sass', 'advanced-faq-creator-by-category' ),
					'fas fa-save' => esc_attr__( 'save', 'advanced-faq-creator-by-category' ),
					'far fa-save' => esc_attr__( 'save', 'advanced-faq-creator-by-category' ),
					'fab fa-schlix' => esc_attr__( 'schlix', 'advanced-faq-creator-by-category' ),
					'fab fa-scribd' => esc_attr__( 'scribd', 'advanced-faq-creator-by-category' ),
					'fas fa-search' => esc_attr__( 'search', 'advanced-faq-creator-by-category' ),
					'fas fa-search-minus' => esc_attr__( 'search-minus', 'advanced-faq-creator-by-category' ),
					'fas fa-search-plus' => esc_attr__( 'search-plus', 'advanced-faq-creator-by-category' ),
					'fab fa-searchengin' => esc_attr__( 'searchengin', 'advanced-faq-creator-by-category' ),
					'fas fa-seedling' => esc_attr__( 'seedling', 'advanced-faq-creator-by-category' ),
					'fab fa-sellcast' => esc_attr__( 'sellcast', 'advanced-faq-creator-by-category' ),
					'fab fa-sellsy' => esc_attr__( 'sellsy', 'advanced-faq-creator-by-category' ),
					'fas fa-server' => esc_attr__( 'server', 'advanced-faq-creator-by-category' ),
					'fab fa-servicestack' => esc_attr__( 'servicestack', 'advanced-faq-creator-by-category' ),
					'fas fa-share' => esc_attr__( 'share', 'advanced-faq-creator-by-category' ),
					'fas fa-share-alt' => esc_attr__( 'share-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-share-alt-square' => esc_attr__( 'share-alt-square', 'advanced-faq-creator-by-category' ),
					'fas fa-share-square' => esc_attr__( 'share-square', 'advanced-faq-creator-by-category' ),
					'far fa-share-square' => esc_attr__( 'share-square', 'advanced-faq-creator-by-category' ),
					'fas fa-shekel-sign' => esc_attr__( 'shekel-sign', 'advanced-faq-creator-by-category' ),
					'fas fa-shield-alt' => esc_attr__( 'shield-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-ship' => esc_attr__( 'ship', 'advanced-faq-creator-by-category' ),
					'fas fa-shipping-fast' => esc_attr__( 'shipping-fast', 'advanced-faq-creator-by-category' ),
					'fab fa-shirtsinbulk' => esc_attr__( 'shirtsinbulk', 'advanced-faq-creator-by-category' ),
					'fas fa-shopping-bag' => esc_attr__( 'shopping-bag', 'advanced-faq-creator-by-category' ),
					'fas fa-shopping-basket' => esc_attr__( 'shopping-basket', 'advanced-faq-creator-by-category' ),
					'fas fa-shopping-cart' => esc_attr__( 'shopping-cart', 'advanced-faq-creator-by-category' ),
					'fas fa-shower' => esc_attr__( 'shower', 'advanced-faq-creator-by-category' ),
					'fas fa-sign' => esc_attr__( 'sign', 'advanced-faq-creator-by-category' ),
					'fas fa-sign-in-alt' => esc_attr__( 'sign-in-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-sign-language' => esc_attr__( 'sign-language', 'advanced-faq-creator-by-category' ),
					'fas fa-sign-out-alt' => esc_attr__( 'sign-out-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-signal' => esc_attr__( 'signal', 'advanced-faq-creator-by-category' ),
					'fab fa-simplybuilt' => esc_attr__( 'simplybuilt', 'advanced-faq-creator-by-category' ),
					'fab fa-sistrix' => esc_attr__( 'sistrix', 'advanced-faq-creator-by-category' ),
					'fas fa-sitemap' => esc_attr__( 'sitemap', 'advanced-faq-creator-by-category' ),
					'fab fa-skyatlas' => esc_attr__( 'skyatlas', 'advanced-faq-creator-by-category' ),
					'fab fa-skype' => esc_attr__( 'skype', 'advanced-faq-creator-by-category' ),
					'fab fa-slack' => esc_attr__( 'slack', 'advanced-faq-creator-by-category' ),
					'fab fa-slack-hash' => esc_attr__( 'slack-hash', 'advanced-faq-creator-by-category' ),
					'fas fa-sliders-h' => esc_attr__( 'sliders-h', 'advanced-faq-creator-by-category' ),
					'fab fa-slideshare' => esc_attr__( 'slideshare', 'advanced-faq-creator-by-category' ),
					'fas fa-smile' => esc_attr__( 'smile', 'advanced-faq-creator-by-category' ),
					'far fa-smile' => esc_attr__( 'smile', 'advanced-faq-creator-by-category' ),
					'fas fa-smoking' => esc_attr__( 'smoking', 'advanced-faq-creator-by-category' ),
					'fab fa-snapchat' => esc_attr__( 'snapchat', 'advanced-faq-creator-by-category' ),
					'fab fa-snapchat-ghost' => esc_attr__( 'snapchat-ghost', 'advanced-faq-creator-by-category' ),
					'fab fa-snapchat-square' => esc_attr__( 'snapchat-square', 'advanced-faq-creator-by-category' ),
					'fas fa-snowflake' => esc_attr__( 'snowflake', 'advanced-faq-creator-by-category' ),
					'far fa-snowflake' => esc_attr__( 'snowflake', 'advanced-faq-creator-by-category' ),
					'fas fa-sort' => esc_attr__( 'sort', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-alpha-down' => esc_attr__( 'sort-alpha-down', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-alpha-up' => esc_attr__( 'sort-alpha-up', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-amount-down' => esc_attr__( 'sort-amount-down', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-amount-up' => esc_attr__( 'sort-amount-up', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-down' => esc_attr__( 'sort-down', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-numeric-down' => esc_attr__( 'sort-numeric-down', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-numeric-up' => esc_attr__( 'sort-numeric-up', 'advanced-faq-creator-by-category' ),
					'fas fa-sort-up' => esc_attr__( 'sort-up', 'advanced-faq-creator-by-category' ),
					'fab fa-soundcloud' => esc_attr__( 'soundcloud', 'advanced-faq-creator-by-category' ),
					'fas fa-space-shuttle' => esc_attr__( 'space-shuttle', 'advanced-faq-creator-by-category' ),
					'fab fa-speakap' => esc_attr__( 'speakap', 'advanced-faq-creator-by-category' ),
					'fas fa-spinner' => esc_attr__( 'spinner', 'advanced-faq-creator-by-category' ),
					'fab fa-spotify' => esc_attr__( 'spotify', 'advanced-faq-creator-by-category' ),
					'fas fa-square' => esc_attr__( 'square', 'advanced-faq-creator-by-category' ),
					'far fa-square' => esc_attr__( 'square', 'advanced-faq-creator-by-category' ),
					'fas fa-square-full' => esc_attr__( 'square-full', 'advanced-faq-creator-by-category' ),
					'fab fa-stack-exchange' => esc_attr__( 'stack-exchange', 'advanced-faq-creator-by-category' ),
					'fab fa-stack-overflow' => esc_attr__( 'stack-overflow', 'advanced-faq-creator-by-category' ),
					'fas fa-star' => esc_attr__( 'star', 'advanced-faq-creator-by-category' ),
					'far fa-star' => esc_attr__( 'star', 'advanced-faq-creator-by-category' ),
					'fas fa-star-half' => esc_attr__( 'star-half', 'advanced-faq-creator-by-category' ),
					'far fa-star-half' => esc_attr__( 'star-half', 'advanced-faq-creator-by-category' ),
					'fab fa-staylinked' => esc_attr__( 'staylinked', 'advanced-faq-creator-by-category' ),
					'fab fa-steam' => esc_attr__( 'steam', 'advanced-faq-creator-by-category' ),
					'fab fa-steam-square' => esc_attr__( 'steam-square', 'advanced-faq-creator-by-category' ),
					'fab fa-steam-symbol' => esc_attr__( 'steam-symbol', 'advanced-faq-creator-by-category' ),
					'fas fa-step-backward' => esc_attr__( 'step-backward', 'advanced-faq-creator-by-category' ),
					'fas fa-step-forward' => esc_attr__( 'step-forward', 'advanced-faq-creator-by-category' ),
					'fas fa-stethoscope' => esc_attr__( 'stethoscope', 'advanced-faq-creator-by-category' ),
					'fab fa-sticker-mule' => esc_attr__( 'sticker-mule', 'advanced-faq-creator-by-category' ),
					'fas fa-sticky-note' => esc_attr__( 'sticky-note', 'advanced-faq-creator-by-category' ),
					'far fa-sticky-note' => esc_attr__( 'sticky-note', 'advanced-faq-creator-by-category' ),
					'fas fa-stop' => esc_attr__( 'stop', 'advanced-faq-creator-by-category' ),
					'fas fa-stop-circle' => esc_attr__( 'stop-circle', 'advanced-faq-creator-by-category' ),
					'far fa-stop-circle' => esc_attr__( 'stop-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-stopwatch' => esc_attr__( 'stopwatch', 'advanced-faq-creator-by-category' ),
					'fab fa-strava' => esc_attr__( 'strava', 'advanced-faq-creator-by-category' ),
					'fas fa-street-view' => esc_attr__( 'street-view', 'advanced-faq-creator-by-category' ),
					'fas fa-strikethrough' => esc_attr__( 'strikethrough', 'advanced-faq-creator-by-category' ),
					'fab fa-stripe' => esc_attr__( 'stripe', 'advanced-faq-creator-by-category' ),
					'fab fa-stripe-s' => esc_attr__( 'stripe-s', 'advanced-faq-creator-by-category' ),
					'fab fa-studiovinari' => esc_attr__( 'studiovinari', 'advanced-faq-creator-by-category' ),
					'fab fa-stumbleupon' => esc_attr__( 'stumbleupon', 'advanced-faq-creator-by-category' ),
					'fab fa-stumbleupon-circle' => esc_attr__( 'stumbleupon-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-subscript' => esc_attr__( 'subscript', 'advanced-faq-creator-by-category' ),
					'fas fa-subway' => esc_attr__( 'subway', 'advanced-faq-creator-by-category' ),
					'fas fa-suitcase' => esc_attr__( 'suitcase', 'advanced-faq-creator-by-category' ),
					'fas fa-sun' => esc_attr__( 'sun', 'advanced-faq-creator-by-category' ),
					'far fa-sun' => esc_attr__( 'sun', 'advanced-faq-creator-by-category' ),
					'fab fa-superpowers' => esc_attr__( 'superpowers', 'advanced-faq-creator-by-category' ),
					'fas fa-superscript' => esc_attr__( 'superscript', 'advanced-faq-creator-by-category' ),
					'fab fa-supple' => esc_attr__( 'supple', 'advanced-faq-creator-by-category' ),
					'fas fa-sync' => esc_attr__( 'sync', 'advanced-faq-creator-by-category' ),
					'fas fa-sync-alt' => esc_attr__( 'sync-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-syringe' => esc_attr__( 'syringe', 'advanced-faq-creator-by-category' ),
					'fas fa-table' => esc_attr__( 'table', 'advanced-faq-creator-by-category' ),
					'fas fa-table-tennis' => esc_attr__( 'table-tennis', 'advanced-faq-creator-by-category' ),
					'fas fa-tablet' => esc_attr__( 'tablet', 'advanced-faq-creator-by-category' ),
					'fas fa-tablet-alt' => esc_attr__( 'tablet-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-tablets' => esc_attr__( 'tablets', 'advanced-faq-creator-by-category' ),
					'fas fa-tachometer-alt' => esc_attr__( 'tachometer-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-tag' => esc_attr__( 'tag', 'advanced-faq-creator-by-category' ),
					'fas fa-tags' => esc_attr__( 'tags', 'advanced-faq-creator-by-category' ),
					'fas fa-tape' => esc_attr__( 'tape', 'advanced-faq-creator-by-category' ),
					'fas fa-tasks' => esc_attr__( 'tasks', 'advanced-faq-creator-by-category' ),
					'fas fa-taxi' => esc_attr__( 'taxi', 'advanced-faq-creator-by-category' ),
					'fab fa-telegram' => esc_attr__( 'telegram', 'advanced-faq-creator-by-category' ),
					'fab fa-telegram-plane' => esc_attr__( 'telegram-plane', 'advanced-faq-creator-by-category' ),
					'fab fa-tencent-weibo' => esc_attr__( 'tencent-weibo', 'advanced-faq-creator-by-category' ),
					'fas fa-terminal' => esc_attr__( 'terminal', 'advanced-faq-creator-by-category' ),
					'fas fa-text-height' => esc_attr__( 'text-height', 'advanced-faq-creator-by-category' ),
					'fas fa-text-width' => esc_attr__( 'text-width', 'advanced-faq-creator-by-category' ),
					'fas fa-th' => esc_attr__( 'th', 'advanced-faq-creator-by-category' ),
					'fas fa-th-large' => esc_attr__( 'th-large', 'advanced-faq-creator-by-category' ),
					'fas fa-th-list' => esc_attr__( 'th-list', 'advanced-faq-creator-by-category' ),
					'fab fa-themeisle' => esc_attr__( 'themeisle', 'advanced-faq-creator-by-category' ),
					'fas fa-thermometer' => esc_attr__( 'thermometer', 'advanced-faq-creator-by-category' ),
					'fas fa-thermometer-empty' => esc_attr__( 'thermometer-empty', 'advanced-faq-creator-by-category' ),
					'fas fa-thermometer-full' => esc_attr__( 'thermometer-full', 'advanced-faq-creator-by-category' ),
					'fas fa-thermometer-half' => esc_attr__( 'thermometer-half', 'advanced-faq-creator-by-category' ),
					'fas fa-thermometer-quarter' => esc_attr__( 'thermometer-quarter', 'advanced-faq-creator-by-category' ),
					'fas fa-thermometer-three-quarters' => esc_attr__( 'thermometer-three-quarters', 'advanced-faq-creator-by-category' ),
					'fas fa-thumbs-down' => esc_attr__( 'thumbs-down', 'advanced-faq-creator-by-category' ),
					'far fa-thumbs-down' => esc_attr__( 'thumbs-down', 'advanced-faq-creator-by-category' ),
					'fas fa-thumbs-up' => esc_attr__( 'thumbs-up', 'advanced-faq-creator-by-category' ),
					'far fa-thumbs-up' => esc_attr__( 'thumbs-up', 'advanced-faq-creator-by-category' ),
					'fas fa-thumbtack' => esc_attr__( 'thumbtack', 'advanced-faq-creator-by-category' ),
					'fas fa-ticket-alt' => esc_attr__( 'ticket-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-times' => esc_attr__( 'times', 'advanced-faq-creator-by-category' ),
					'fas fa-times-circle' => esc_attr__( 'times-circle', 'advanced-faq-creator-by-category' ),
					'far fa-times-circle' => esc_attr__( 'times-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-tint' => esc_attr__( 'tint', 'advanced-faq-creator-by-category' ),
					'fas fa-toggle-off' => esc_attr__( 'toggle-off', 'advanced-faq-creator-by-category' ),
					'fas fa-toggle-on' => esc_attr__( 'toggle-on', 'advanced-faq-creator-by-category' ),
					'fas fa-trademark' => esc_attr__( 'trademark', 'advanced-faq-creator-by-category' ),
					'fas fa-train' => esc_attr__( 'train', 'advanced-faq-creator-by-category' ),
					'fas fa-transgender' => esc_attr__( 'transgender', 'advanced-faq-creator-by-category' ),
					'fas fa-transgender-alt' => esc_attr__( 'transgender-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-trash' => esc_attr__( 'trash', 'advanced-faq-creator-by-category' ),
					'fas fa-trash-alt' => esc_attr__( 'trash-alt', 'advanced-faq-creator-by-category' ),
					'far fa-trash-alt' => esc_attr__( 'trash-alt', 'advanced-faq-creator-by-category' ),
					'fas fa-tree' => esc_attr__( 'tree', 'advanced-faq-creator-by-category' ),
					'fab fa-trello' => esc_attr__( 'trello', 'advanced-faq-creator-by-category' ),
					'fab fa-tripadvisor' => esc_attr__( 'tripadvisor', 'advanced-faq-creator-by-category' ),
					'fas fa-trophy' => esc_attr__( 'trophy', 'advanced-faq-creator-by-category' ),
					'fas fa-truck' => esc_attr__( 'truck', 'advanced-faq-creator-by-category' ),
					'fas fa-truck-loading' => esc_attr__( 'truck-loading', 'advanced-faq-creator-by-category' ),
					'fas fa-truck-moving' => esc_attr__( 'truck-moving', 'advanced-faq-creator-by-category' ),
					'fas fa-tty' => esc_attr__( 'tty', 'advanced-faq-creator-by-category' ),
					'fab fa-tumblr' => esc_attr__( 'tumblr', 'advanced-faq-creator-by-category' ),
					'fab fa-tumblr-square' => esc_attr__( 'tumblr-square', 'advanced-faq-creator-by-category' ),
					'fas fa-tv' => esc_attr__( 'tv', 'advanced-faq-creator-by-category' ),
					'fab fa-twitch' => esc_attr__( 'twitch', 'advanced-faq-creator-by-category' ),
					'fab fa-twitter' => esc_attr__( 'twitter', 'advanced-faq-creator-by-category' ),
					'fab fa-twitter-square' => esc_attr__( 'twitter-square', 'advanced-faq-creator-by-category' ),
					'fab fa-typo3' => esc_attr__( 'typo3', 'advanced-faq-creator-by-category' ),
					'fab fa-uber' => esc_attr__( 'uber', 'advanced-faq-creator-by-category' ),
					'fab fa-uikit' => esc_attr__( 'uikit', 'advanced-faq-creator-by-category' ),
					'fas fa-umbrella' => esc_attr__( 'umbrella', 'advanced-faq-creator-by-category' ),
					'fas fa-underline' => esc_attr__( 'underline', 'advanced-faq-creator-by-category' ),
					'fas fa-undo' => esc_attr__( 'undo', 'advanced-faq-creator-by-category' ),
					'fas fa-undo-alt' => esc_attr__( 'undo-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-uniregistry' => esc_attr__( 'uniregistry', 'advanced-faq-creator-by-category' ),
					'fas fa-universal-access' => esc_attr__( 'universal-access', 'advanced-faq-creator-by-category' ),
					'fas fa-university' => esc_attr__( 'university', 'advanced-faq-creator-by-category' ),
					'fas fa-unlink' => esc_attr__( 'unlink', 'advanced-faq-creator-by-category' ),
					'fas fa-unlock' => esc_attr__( 'unlock', 'advanced-faq-creator-by-category' ),
					'fas fa-unlock-alt' => esc_attr__( 'unlock-alt', 'advanced-faq-creator-by-category' ),
					'fab fa-untappd' => esc_attr__( 'untappd', 'advanced-faq-creator-by-category' ),
					'fas fa-upload' => esc_attr__( 'upload', 'advanced-faq-creator-by-category' ),
					'fab fa-usb' => esc_attr__( 'usb', 'advanced-faq-creator-by-category' ),
					'fas fa-user' => esc_attr__( 'user', 'advanced-faq-creator-by-category' ),
					'far fa-user' => esc_attr__( 'user', 'advanced-faq-creator-by-category' ),
					'fas fa-user-circle' => esc_attr__( 'user-circle', 'advanced-faq-creator-by-category' ),
					'far fa-user-circle' => esc_attr__( 'user-circle', 'advanced-faq-creator-by-category' ),
					'fas fa-user-md' => esc_attr__( 'user-md', 'advanced-faq-creator-by-category' ),
					'fas fa-user-plus' => esc_attr__( 'user-plus', 'advanced-faq-creator-by-category' ),
					'fas fa-user-secret' => esc_attr__( 'user-secret', 'advanced-faq-creator-by-category' ),
					'fas fa-user-times' => esc_attr__( 'user-times', 'advanced-faq-creator-by-category' ),
					'fas fa-users' => esc_attr__( 'users', 'advanced-faq-creator-by-category' ),
					'fab fa-ussunnah' => esc_attr__( 'ussunnah', 'advanced-faq-creator-by-category' ),
					'fas fa-utensil-spoon' => esc_attr__( 'utensil-spoon', 'advanced-faq-creator-by-category' ),
					'fas fa-utensils' => esc_attr__( 'utensils', 'advanced-faq-creator-by-category' ),
					'fab fa-vaadin' => esc_attr__( 'vaadin', 'advanced-faq-creator-by-category' ),
					'fas fa-venus' => esc_attr__( 'venus', 'advanced-faq-creator-by-category' ),
					'fas fa-venus-double' => esc_attr__( 'venus-double', 'advanced-faq-creator-by-category' ),
					'fas fa-venus-mars' => esc_attr__( 'venus-mars', 'advanced-faq-creator-by-category' ),
					'fab fa-viacoin' => esc_attr__( 'viacoin', 'advanced-faq-creator-by-category' ),
					'fab fa-viadeo' => esc_attr__( 'viadeo', 'advanced-faq-creator-by-category' ),
					'fab fa-viadeo-square' => esc_attr__( 'viadeo-square', 'advanced-faq-creator-by-category' ),
					'fas fa-vial' => esc_attr__( 'vial', 'advanced-faq-creator-by-category' ),
					'fas fa-vials' => esc_attr__( 'vials', 'advanced-faq-creator-by-category' ),
					'fab fa-viber' => esc_attr__( 'viber', 'advanced-faq-creator-by-category' ),
					'fas fa-video' => esc_attr__( 'video', 'advanced-faq-creator-by-category' ),
					'fas fa-video-slash' => esc_attr__( 'video-slash', 'advanced-faq-creator-by-category' ),
					'fab fa-vimeo' => esc_attr__( 'vimeo', 'advanced-faq-creator-by-category' ),
					'fab fa-vimeo-square' => esc_attr__( 'vimeo-square', 'advanced-faq-creator-by-category' ),
					'fab fa-vimeo-v' => esc_attr__( 'vimeo-v', 'advanced-faq-creator-by-category' ),
					'fab fa-vine' => esc_attr__( 'vine', 'advanced-faq-creator-by-category' ),
					'fab fa-vk' => esc_attr__( 'vk', 'advanced-faq-creator-by-category' ),
					'fab fa-vnv' => esc_attr__( 'vnv', 'advanced-faq-creator-by-category' ),
					'fas fa-volleyball-ball' => esc_attr__( 'volleyball-ball', 'advanced-faq-creator-by-category' ),
					'fas fa-volume-down' => esc_attr__( 'volume-down', 'advanced-faq-creator-by-category' ),
					'fas fa-volume-off' => esc_attr__( 'volume-off', 'advanced-faq-creator-by-category' ),
					'fas fa-volume-up' => esc_attr__( 'volume-up', 'advanced-faq-creator-by-category' ),
					'fab fa-vuejs' => esc_attr__( 'vuejs', 'advanced-faq-creator-by-category' ),
					'fas fa-warehouse' => esc_attr__( 'warehouse', 'advanced-faq-creator-by-category' ),
					'fab fa-weibo' => esc_attr__( 'weibo', 'advanced-faq-creator-by-category' ),
					'fas fa-weight' => esc_attr__( 'weight', 'advanced-faq-creator-by-category' ),
					'fab fa-weixin' => esc_attr__( 'weixin', 'advanced-faq-creator-by-category' ),
					'fab fa-whatsapp' => esc_attr__( 'whatsapp', 'advanced-faq-creator-by-category' ),
					'fab fa-whatsapp-square' => esc_attr__( 'whatsapp-square', 'advanced-faq-creator-by-category' ),
					'fas fa-wheelchair' => esc_attr__( 'wheelchair', 'advanced-faq-creator-by-category' ),
					'fab fa-whmcs' => esc_attr__( 'whmcs', 'advanced-faq-creator-by-category' ),
					'fas fa-wifi' => esc_attr__( 'wifi', 'advanced-faq-creator-by-category' ),
					'fab fa-wikipedia-w' => esc_attr__( 'wikipedia-w', 'advanced-faq-creator-by-category' ),
					'fas fa-window-close' => esc_attr__( 'window-close', 'advanced-faq-creator-by-category' ),
					'far fa-window-close' => esc_attr__( 'window-close', 'advanced-faq-creator-by-category' ),
					'fas fa-window-maximize' => esc_attr__( 'window-maximize', 'advanced-faq-creator-by-category' ),
					'far fa-window-maximize' => esc_attr__( 'window-maximize', 'advanced-faq-creator-by-category' ),
					'fas fa-window-minimize' => esc_attr__( 'window-minimize', 'advanced-faq-creator-by-category' ),
					'far fa-window-minimize' => esc_attr__( 'window-minimize', 'advanced-faq-creator-by-category' ),
					'fas fa-window-restore' => esc_attr__( 'window-restore', 'advanced-faq-creator-by-category' ),
					'far fa-window-restore' => esc_attr__( 'window-restore', 'advanced-faq-creator-by-category' ),
					'fab fa-windows' => esc_attr__( 'windows', 'advanced-faq-creator-by-category' ),
					'fas fa-wine-glass' => esc_attr__( 'wine-glass', 'advanced-faq-creator-by-category' ),
					'fas fa-won-sign' => esc_attr__( 'won-sign', 'advanced-faq-creator-by-category' ),
					'fab fa-wordpress' => esc_attr__( 'wordpress', 'advanced-faq-creator-by-category' ),
					'fab fa-wordpress-simple' => esc_attr__( 'wordpress-simple', 'advanced-faq-creator-by-category' ),
					'fab fa-wpbeginner' => esc_attr__( 'wpbeginner', 'advanced-faq-creator-by-category' ),
					'fab fa-wpexplorer' => esc_attr__( 'wpexplorer', 'advanced-faq-creator-by-category' ),
					'fab fa-wpforms' => esc_attr__( 'wpforms', 'advanced-faq-creator-by-category' ),
					'fas fa-wrench' => esc_attr__( 'wrench', 'advanced-faq-creator-by-category' ),
					'fas fa-x-ray' => esc_attr__( 'x-ray', 'advanced-faq-creator-by-category' ),
					'fab fa-xbox' => esc_attr__( 'xbox', 'advanced-faq-creator-by-category' ),
					'fab fa-xing' => esc_attr__( 'xing', 'advanced-faq-creator-by-category' ),
					'fab fa-xing-square' => esc_attr__( 'xing-square', 'advanced-faq-creator-by-category' ),
					'fab fa-y-combinator' => esc_attr__( 'y-combinator', 'advanced-faq-creator-by-category' ),
					'fab fa-yahoo' => esc_attr__( 'yahoo', 'advanced-faq-creator-by-category' ),
					'fab fa-yandex' => esc_attr__( 'yandex', 'advanced-faq-creator-by-category' ),
					'fab fa-yandex-international' => esc_attr__( 'yandex-international', 'advanced-faq-creator-by-category' ),
					'fab fa-yelp' => esc_attr__( 'yelp', 'advanced-faq-creator-by-category' ),
					'fas fa-yen-sign' => esc_attr__( 'yen-sign', 'advanced-faq-creator-by-category' ),
					'fab fa-yoast' => esc_attr__( 'yoast', 'advanced-faq-creator-by-category' ),
					'fab fa-youtube' => esc_attr__( 'youtube', 'advanced-faq-creator-by-category' ),
					'fab fa-youtube-square' => esc_attr__( 'youtube-square', 'advanced-faq-creator-by-category' ),
				);
	}
			/*
* مكتبات الستايل الجافا سكرت
*/
		public function faq_css($hook) {
            wp_enqueue_style('font-awesome-all', AFAQCBC_PLUGIN_URL.'/assets/css/all.css');
            wp_enqueue_style('select2-min', AFAQCBC_PLUGIN_URL . 'assets/css/select2.min.css');
			wp_enqueue_script('select2-js', AFAQCBC_PLUGIN_URL . 'assets/js/select2.min.js', array('jquery'), '4.0', false);

        }
				/*
* كواد الجافا سكربت الخاصه بالصفحه 
*/
		public function sitting_field_js() {

			// Print js only once per page
			if ( did_action( 'Psost_Metabox_sitting_field_color_jss_new_q' ) >= 1 ) {
				return;
			}
			?>
			<script type="text/javascript">
			"use strict";
				jQuery(document).ready(function($){
					"use strict";
					jQuery('#q_icon_color').wpColorPicker();
				});
				function formatText (icon) {
					"use strict";
					return jQuery('<span><i class="' + jQuery(icon.element).data('icon') + '"></i> ' + icon.text + '</span>');
				};

				jQuery('.select2-icon').select2({
					width: "100%",
					templateSelection: formatText,
					templateResult: formatText
				});
				<?php
				if ( isset($_GET['tag_ID']) && is_numeric($_GET['tag_ID']) ) {
					$catId = intval($_GET['tag_ID']);
					?>
					
						jQuery(function() {
							"use strict";
							var catId = <?php echo esc_js(json_encode($catId)); ?>;
							jQuery('#in-faqs-' + catId).click();
						});
					
					<?php
				}
				?>
			</script>
			

			<?php
			do_action( 'Psost_Metabox_sitting_field_color_jss_new_q', $this );

		}

		



	}

	new AFAQCBC_q_a_faq_Setting_Question_Metabox;

 }